-- Some things you would need to implement:
-- 1. Getting the weapon's degradation
-- 2. Getting the weapon's current stats with components applied
local function getWeaponStats(weapon, component)
    local weaponItem = ItemDatabase.new(weapon)
    if not weaponItem then return end

    local componentItem = nil
    if component ~= 0 then
        componentItem = ItemDatabase.new(component)
    end

    -- Base stats
    local baseStats = {
        damage = 0,
        range = 0,
        fireRate = 0,
        reload = 0,
        accuracy = 0
    }

    -- Get weapon familiarity
    local familiarityMult = 100
    local struct = DataView.ArrayBuffer(16)
    struct:SetInt32(0, `skill`)
    struct:SetInt32(8, GetWeaponStatId(weapon))

    if Citizen.InvokeNative(0xC48FE1971C9743FF, struct:Buffer()) == 1 then
        familiarityMult = Citizen.InvokeNative(0xD7AE6C9C9C6AC54D, struct:Buffer(), Citizen.ResultAsFloat())
    end

    local weaponEffects = weaponItem:GetStats()
    for key, effect in pairs(weaponEffects) do
        if key == "weaponDamage" then
            baseStats.damage += effect.Value
        elseif key == "weaponRange" then
            baseStats.range += effect.Value
        elseif key == "weaponFireRate" then
            baseStats.fireRate += effect.Value
        elseif key == "weaponReload" then
            baseStats.reload += effect.Value
        elseif key == "weaponAccuracy" then
            baseStats.accuracy += effect.Value
        end

        -- Applies a skill bonus based on the weapon familiarity
        if key == "familiarityRange" then
            baseStats.range += math.floor(effect.Value * (familiarityMult / 100))
        elseif key == "familiarityReload" then
            baseStats.reload += math.floor(effect.Value * (familiarityMult / 100))
        elseif key == "familiarityAccuracy" then
            baseStats.accuracy += math.floor(effect.Value * (familiarityMult / 100))
        end
    end

    local currentBonus = { damage = 0, accuracy = 0, range = 0 }

    -- TODO: Iterate through all equipped components on the weapon
    -- You'll need a list of all applied components, and then do the same as below for each item
    -- You should add each effect value to the currentBonus

    local potentialBonus = { damage = 0, accuracy = 0, range = 0 }

    -- Process preview component effects if a component is provided
    if componentItem then
        local componentEffects = componentItem:GetStats()

        if componentItem:IsInGroup("AMMO") then
            for key, effect in pairs(componentEffects) do
                if key == "statModifierDamage" then
                    baseStats.damage += effect.Value
                elseif key == "statModifierAccuracy" then
                    baseStats.accuracy += effect.Value
                elseif key == "statModifierRange" then
                    baseStats.range += effect.Value
                end
            end
        else
            for key, effect in pairs(componentEffects) do
                if key == "statModifierDamage" then
                    potentialBonus.damage += effect.Value
                elseif key == "statModifierAccuracy" then
                    potentialBonus.accuracy += effect.Value
                elseif key == "statModifierRange" then
                    potentialBonus.range += effect.Value
                end
            end
        end
    end

    local finalStat = {
        damage = baseStats.damage + currentBonus.damage,
        range = baseStats.range + currentBonus.range,
        accuracy = baseStats.accuracy + currentBonus.accuracy,
        fireRate = baseStats.fireRate,
        reload = baseStats.reload
    }

    local projectedStat = {
        damage = baseStats.damage + potentialBonus.damage,
        range = baseStats.range + potentialBonus.range,
        accuracy = baseStats.accuracy + potentialBonus.accuracy
    }

    local maxDisplay = {
        damage = math.max(finalStat.damage, projectedStat.damage),
        range = math.max(finalStat.range, projectedStat.range),
        accuracy = math.max(finalStat.accuracy, projectedStat.accuracy)
    }

    -- TODO: Get this weapon's degradation
    local degradation = 0
    local degradationPenalty = math.ceil(degradation * 10.0)

    -- Apply penalty to current actuals
    finalStat.damage = finalStat.damage - degradationPenalty
    finalStat.fireRate = finalStat.fireRate - degradationPenalty
    finalStat.reload = finalStat.reload - degradationPenalty

    -- Apply penalty to projected stats
    projectedStat.damage = projectedStat.damage - degradationPenalty

    return {
        Power = {
            Value = projectedStat.damage,
            Diff = maxDisplay.damage,
            New = finalStat.damage,
        },
        Range = {
            Value = projectedStat.range,
            Diff = maxDisplay.range,
            New = finalStat.range,
        },
        Accuracy = {
            Value = projectedStat.accuracy,
            Diff = maxDisplay.accuracy,
            New = finalStat.accuracy,
        },
        FireRate = {
            Value = finalStat.fireRate,
            Diff = baseStats.fireRate,
            New = finalStat.fireRate,
        },
        Reload = {
            Value = finalStat.reload,
            Diff = baseStats.reload,
            New = finalStat.reload,
        },
    }
end

-- Used for the main list of weapons in the Gunsmith
local MODIFIABLE_WEAPONS <const> = {
    { Id = "WEAPON_BOW_IMPROVED",             Type = "BOW" },
    { Id = "WEAPON_REVOLVER_NAVY",            Type = "REVOLVER" },
    { Id = "WEAPON_REVOLVER_LEMAT",           Type = "REVOLVER" },
    { Id = "WEAPON_REVOLVER_CATTLEMAN",       Type = "REVOLVER" },
    { Id = "WEAPON_REVOLVER_DOUBLEACTION",    Type = "REVOLVER" },
    { Id = "WEAPON_REVOLVER_SCHOFIELD",       Type = "REVOLVER" },
    { Id = "WEAPON_PISTOL_M1899",             Type = "PISTOL" },
    { Id = "WEAPON_PISTOL_VOLCANIC",          Type = "PISTOL" },
    { Id = "WEAPON_PISTOL_SEMIAUTO",          Type = "PISTOL" },
    { Id = "WEAPON_PISTOL_MAUSER",            Type = "PISTOL" },
    { Id = "WEAPON_REPEATER_EVANS",           Type = "REPEATER" },
    { Id = "WEAPON_REPEATER_CARBINE",         Type = "REPEATER" },
    { Id = "WEAPON_REPEATER_WINCHESTER",      Type = "REPEATER" },
    { Id = "WEAPON_REPEATER_HENRY",           Type = "REPEATER" },
    { Id = "WEAPON_RIFLE_ELEPHANT",           Type = "RIFLE" },
    { Id = "WEAPON_RIFLE_VARMINT",            Type = "RIFLE" },
    { Id = "WEAPON_RIFLE_SPRINGFIELD",        Type = "RIFLE" },
    { Id = "WEAPON_RIFLE_BOLTACTION",         Type = "RIFLE" },
    { Id = "WEAPON_SNIPERRIFLE_ROLLINGBLOCK", Type = "RIFLE" },
    { Id = "WEAPON_SNIPERRIFLE_CARCANO",      Type = "RIFLE" },
    { Id = "WEAPON_SHOTGUN_SAWEDOFF",         Type = "SHOTGUN" },
    { Id = "WEAPON_SHOTGUN_DOUBLEBARREL",     Type = "SHOTGUN" },
    { Id = "WEAPON_SHOTGUN_PUMP",             Type = "SHOTGUN" },
    { Id = "WEAPON_SHOTGUN_SEMIAUTO",         Type = "SHOTGUN" },
    { Id = "WEAPON_SHOTGUN_REPEATING",        Type = "SHOTGUN" },
    { Id = "WEAPON_MELEE_KNIFE",              Type = "MELEE" },
}

-- Shared long arm components, shared meaning the majority of the weapons use these
local SHARED_LONGARM_BARREL_RIFLING <const> = { "COMPONENT_LONGARM_BARREL_RIFLING_NONE", "COMPONENT_LONGARM_BARREL_RIFLING_1" }
local SHARED_LONGARM_BARREL_MATERIAL <const> = { "COMPONENT_LONGARM_BARREL_MATERIAL_1", "COMPONENT_LONGARM_BARREL_MATERIAL_2", "COMPONENT_LONGARM_BARREL_MATERIAL_3", "COMPONENT_LONGARM_BARREL_MATERIAL_4", "COMPONENT_LONGARM_BARREL_MATERIAL_5", "COMPONENT_LONGARM_BARREL_MATERIAL_6", "COMPONENT_LONGARM_BARREL_MATERIAL_8", "COMPONENT_LONGARM_BARREL_MATERIAL_9", "COMPONENT_LONGARM_BARREL_MATERIAL_7", "COMPONENT_LONGARM_BARREL_MATERIAL_10" }
local SHARED_LONGARM_CYLINDER_MATERIAL <const> = { "COMPONENT_LONGARM_CYLINDER_MATERIAL_1", "COMPONENT_LONGARM_CYLINDER_MATERIAL_2", "COMPONENT_LONGARM_CYLINDER_MATERIAL_3", "COMPONENT_LONGARM_CYLINDER_MATERIAL_4", "COMPONENT_LONGARM_CYLINDER_MATERIAL_5", "COMPONENT_LONGARM_CYLINDER_MATERIAL_6", "COMPONENT_LONGARM_CYLINDER_MATERIAL_8", "COMPONENT_LONGARM_CYLINDER_MATERIAL_9", "COMPONENT_LONGARM_CYLINDER_MATERIAL_7", "COMPONENT_LONGARM_CYLINDER_MATERIAL_10" }
local SHARED_LONGARM_FRAME_MATERIAL <const> = { "COMPONENT_LONGARM_FRAME_MATERIAL_1", "COMPONENT_LONGARM_FRAME_MATERIAL_2", "COMPONENT_LONGARM_FRAME_MATERIAL_3", "COMPONENT_LONGARM_FRAME_MATERIAL_4", "COMPONENT_LONGARM_FRAME_MATERIAL_5", "COMPONENT_LONGARM_FRAME_MATERIAL_6", "COMPONENT_LONGARM_FRAME_MATERIAL_8", "COMPONENT_LONGARM_FRAME_MATERIAL_9", "COMPONENT_LONGARM_FRAME_MATERIAL_7", "COMPONENT_LONGARM_FRAME_MATERIAL_10" }
local SHARED_LONGARM_HAMMER_MATERIAL <const> = { "COMPONENT_LONGARM_HAMMER_MATERIAL_1", "COMPONENT_LONGARM_HAMMER_MATERIAL_2", "COMPONENT_LONGARM_HAMMER_MATERIAL_3", "COMPONENT_LONGARM_HAMMER_MATERIAL_4", "COMPONENT_LONGARM_HAMMER_MATERIAL_5", "COMPONENT_LONGARM_HAMMER_MATERIAL_6", "COMPONENT_LONGARM_HAMMER_MATERIAL_8", "COMPONENT_LONGARM_HAMMER_MATERIAL_9", "COMPONENT_LONGARM_HAMMER_MATERIAL_7", "COMPONENT_LONGARM_HAMMER_MATERIAL_10" }
local SHARED_LONGARM_SIGHT_MATERIAL <const> = { "COMPONENT_LONGARM_SIGHT_MATERIAL_1", "COMPONENT_LONGARM_SIGHT_MATERIAL_2", "COMPONENT_LONGARM_SIGHT_MATERIAL_3", "COMPONENT_LONGARM_SIGHT_MATERIAL_4", "COMPONENT_LONGARM_SIGHT_MATERIAL_5", "COMPONENT_LONGARM_SIGHT_MATERIAL_6", "COMPONENT_LONGARM_SIGHT_MATERIAL_8", "COMPONENT_LONGARM_SIGHT_MATERIAL_9", "COMPONENT_LONGARM_SIGHT_MATERIAL_7", "COMPONENT_LONGARM_SIGHT_MATERIAL_10" }
local SHARED_LONGARM_TRIGGER_MATERIAL <const> = { "COMPONENT_LONGARM_TRIGGER_MATERIAL_1", "COMPONENT_LONGARM_TRIGGER_MATERIAL_2", "COMPONENT_LONGARM_TRIGGER_MATERIAL_3", "COMPONENT_LONGARM_TRIGGER_MATERIAL_4", "COMPONENT_LONGARM_TRIGGER_MATERIAL_5", "COMPONENT_LONGARM_TRIGGER_MATERIAL_6", "COMPONENT_LONGARM_TRIGGER_MATERIAL_8", "COMPONENT_LONGARM_TRIGGER_MATERIAL_9", "COMPONENT_LONGARM_TRIGGER_MATERIAL_7", "COMPONENT_LONGARM_TRIGGER_MATERIAL_10" }
local SHARED_LONGARM_FULL_ENGRAVING <const> = { "COMPONENT_LONGARM_FULL_ENGRAVING_NONE", "COMPONENT_LONGARM_ENGRAVING_1", "COMPONENT_LONGARM_ENGRAVING_2", "COMPONENT_LONGARM_ENGRAVING_3", "COMPONENT_LONGARM_ENGRAVING_4" }
local SHARED_LONGARM_ENGRAVING_MATERIAL <const> = { "COMPONENT_LONGARM_ENGRAVING_MATERIAL_1", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_2", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_3", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_4", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_5", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_6", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_8", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_9", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_7", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_10", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_11", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_12", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_13", "COMPONENT_LONGARM_ENGRAVING_MATERIAL_14" }
local SHARED_LONGARM_BARREL_ENGRAVING <const> = { "COMPONENT_LONGARM_BARREL_ENGRAVING_NONE", "COMPONENT_LONGARM_BARREL_ENGRAVING_1", "COMPONENT_LONGARM_BARREL_ENGRAVING_2", "COMPONENT_LONGARM_BARREL_ENGRAVING_3", "COMPONENT_LONGARM_BARREL_ENGRAVING_4" }
local SHARED_LONGARM_CYLINDER_ENGRAVING <const> = { "COMPONENT_LONGARM_CYLINDER_ENGRAVING_NONE", "COMPONENT_LONGARM_CYLINDER_ENGRAVING_1", "COMPONENT_LONGARM_CYLINDER_ENGRAVING_2", "COMPONENT_LONGARM_CYLINDER_ENGRAVING_3", "COMPONENT_LONGARM_CYLINDER_ENGRAVING_4" }
local SHARED_LONGARM_FRAME_ENGRAVING <const> = { "COMPONENT_LONGARM_FRAME_ENGRAVING_NONE", "COMPONENT_LONGARM_FRAME_ENGRAVING_1", "COMPONENT_LONGARM_FRAME_ENGRAVING_2", "COMPONENT_LONGARM_FRAME_ENGRAVING_3", "COMPONENT_LONGARM_FRAME_ENGRAVING_4" }
local SHARED_LONGARM_CLOTH_WRAP_TINT <const> = { "COMPONENT_LONGARM_WRAP_TINT_B_1", "COMPONENT_LONGARM_WRAP_TINT_B_2", "COMPONENT_LONGARM_WRAP_TINT_B_3", "COMPONENT_LONGARM_WRAP_TINT_B_4", "COMPONENT_LONGARM_WRAP_TINT_B_5", "COMPONENT_LONGARM_WRAP_TINT_B_6", "COMPONENT_LONGARM_WRAP_TINT_B_7", "COMPONENT_LONGARM_WRAP_TINT_B_8", "COMPONENT_LONGARM_WRAP_TINT_C_1", "COMPONENT_LONGARM_WRAP_TINT_C_2", "COMPONENT_LONGARM_WRAP_TINT_C_3", "COMPONENT_LONGARM_WRAP_TINT_C_4", "COMPONENT_LONGARM_WRAP_TINT_C_5", "COMPONENT_LONGARM_WRAP_TINT_C_6", "COMPONENT_LONGARM_WRAP_TINT_C_7", "COMPONENT_LONGARM_WRAP_TINT_C_8", "COMPONENT_LONGARM_WRAP_TINT_C_9", "COMPONENT_LONGARM_WRAP_TINT_D_1", "COMPONENT_LONGARM_WRAP_TINT_D_2", "COMPONENT_LONGARM_WRAP_TINT_D_3", "COMPONENT_LONGARM_WRAP_TINT_D_4", "COMPONENT_LONGARM_WRAP_TINT_D_5", "COMPONENT_LONGARM_WRAP_TINT_D_6", "COMPONENT_LONGARM_WRAP_TINT_D_7", "COMPONENT_LONGARM_WRAP_TINT_D_8", "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_DEFAULT", "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_1", "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_2", "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_3", "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_4", "COMPONENT_LONGARM_WRAP_TINT_POLKADOT_5", "COMPONENT_LONGARM_WRAP_TINT_NATIVE_DEFAULT", "COMPONENT_LONGARM_WRAP_TINT_NATIVE_1", "COMPONENT_LONGARM_WRAP_TINT_NATIVE_2", "COMPONENT_LONGARM_WRAP_TINT_NATIVE_3", "COMPONENT_LONGARM_WRAP_TINT_NATIVE_4", "COMPONENT_LONGARM_WRAP_TINT_NATIVE_5", "COMPONENT_LONGARM_WRAP_TINT_TARTAN_DEFAULT", "COMPONENT_LONGARM_WRAP_TINT_TARTAN_1", "COMPONENT_LONGARM_WRAP_TINT_TARTAN_2", "COMPONENT_LONGARM_WRAP_TINT_TARTAN_3", "COMPONENT_LONGARM_WRAP_TINT_TARTAN_4", "COMPONENT_LONGARM_WRAP_TINT_TARTAN_5" }
local SHARED_LONGARM_LEATHER_WRAP_TINT <const> = { "COMPONENT_LONGARM_WRAP_TINT_A_1", "COMPONENT_LONGARM_WRAP_TINT_A_2", "COMPONENT_LONGARM_WRAP_TINT_A_3", "COMPONENT_LONGARM_WRAP_TINT_A_4", "COMPONENT_LONGARM_WRAP_TINT_A_5", "COMPONENT_LONGARM_WRAP_TINT_A_6", "COMPONENT_LONGARM_WRAP_TINT_A_7", "COMPONENT_LONGARM_WRAP_TINT_A_8", "COMPONENT_LONGARM_WRAP_TINT_WHITE", "COMPONENT_LONGARM_WRAP_TINT_BLACK", "COMPONENT_LONGARM_WRAP_TINT_E_1", "COMPONENT_LONGARM_WRAP_TINT_E_2", "COMPONENT_LONGARM_WRAP_TINT_E_3", "COMPONENT_LONGARM_WRAP_TINT_E_4", "COMPONENT_LONGARM_WRAP_TINT_E_5", "COMPONENT_LONGARM_WRAP_TINT_E_6", "COMPONENT_LONGARM_WRAP_TINT_E_7", "COMPONENT_LONGARM_WRAP_TINT_E_8", "COMPONENT_LONGARM_WRAP_TINT_E_9", "COMPONENT_LONGARM_WRAP_TINT_E_10" }
local SHARED_LONGARM_GRIPSTOCK_ENGRAVING <const> = { "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_NONE", "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_1", "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_2", "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_3", "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_4", "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_5", "COMPONENT_LONGARM_GRIPSTOCK_ENGRAVING_6" }
local SHARED_LONGARM_GRIPSTOCK_TINT <const> = { "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_1", "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_2", "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_3", "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_4", "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_5", "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_6", "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_7", "COMPONENT_LONGARM_GRIPSTOCK_TINT_A_8", "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_1", "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_2", "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_3", "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_4", "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_5", "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_6", "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_7", "COMPONENT_LONGARM_GRIPSTOCK_TINT_B_8", "COMPONENT_LONGARM_GRIPSTOCK_TINT_GRAY_BIRCH" }

-- Shared short arm components, shared meaning the majority of the weapons use these
local SHARED_SHORTARM_BARREL_RIFLING <const> = { "COMPONENT_SHORTARM_BARREL_RIFLING_NONE", "COMPONENT_SHORTARM_BARREL_RIFLING_1" }
local SHARED_SHORTARM_BARREL_MATERIAL <const> = { "COMPONENT_SHORTARM_BARREL_MATERIAL_1", "COMPONENT_SHORTARM_BARREL_MATERIAL_2", "COMPONENT_SHORTARM_BARREL_MATERIAL_3", "COMPONENT_SHORTARM_BARREL_MATERIAL_4", "COMPONENT_SHORTARM_BARREL_MATERIAL_5", "COMPONENT_SHORTARM_BARREL_MATERIAL_6", "COMPONENT_SHORTARM_BARREL_MATERIAL_8", "COMPONENT_SHORTARM_BARREL_MATERIAL_9", "COMPONENT_SHORTARM_BARREL_MATERIAL_7", "COMPONENT_SHORTARM_BARREL_MATERIAL_10" }
local SHARED_SHORTARM_CYLINDER_MATERIAL <const> = { "COMPONENT_SHORTARM_CYLINDER_MATERIAL_1", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_2", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_3", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_4", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_5", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_6", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_8", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_9", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_7", "COMPONENT_SHORTARM_CYLINDER_MATERIAL_10" }
local SHARED_SHORTARM_FRAME_MATERIAL <const> = { "COMPONENT_SHORTARM_FRAME_MATERIAL_1", "COMPONENT_SHORTARM_FRAME_MATERIAL_2", "COMPONENT_SHORTARM_FRAME_MATERIAL_3", "COMPONENT_SHORTARM_FRAME_MATERIAL_4", "COMPONENT_SHORTARM_FRAME_MATERIAL_5", "COMPONENT_SHORTARM_FRAME_MATERIAL_6", "COMPONENT_SHORTARM_FRAME_MATERIAL_8", "COMPONENT_SHORTARM_FRAME_MATERIAL_9", "COMPONENT_SHORTARM_FRAME_MATERIAL_7", "COMPONENT_SHORTARM_FRAME_MATERIAL_10" }
local SHARED_SHORTARM_HAMMER_MATERIAL <const> = { "COMPONENT_SHORTARM_HAMMER_MATERIAL_1", "COMPONENT_SHORTARM_HAMMER_MATERIAL_2", "COMPONENT_SHORTARM_HAMMER_MATERIAL_3", "COMPONENT_SHORTARM_HAMMER_MATERIAL_4", "COMPONENT_SHORTARM_HAMMER_MATERIAL_5", "COMPONENT_SHORTARM_HAMMER_MATERIAL_6", "COMPONENT_SHORTARM_HAMMER_MATERIAL_8", "COMPONENT_SHORTARM_HAMMER_MATERIAL_9", "COMPONENT_SHORTARM_HAMMER_MATERIAL_7", "COMPONENT_SHORTARM_HAMMER_MATERIAL_10" }
local SHARED_SHORTARM_SIGHT_MATERIAL <const> = { "COMPONENT_SHORTARM_SIGHT_MATERIAL_1", "COMPONENT_SHORTARM_SIGHT_MATERIAL_2", "COMPONENT_SHORTARM_SIGHT_MATERIAL_3", "COMPONENT_SHORTARM_SIGHT_MATERIAL_4", "COMPONENT_SHORTARM_SIGHT_MATERIAL_5", "COMPONENT_SHORTARM_SIGHT_MATERIAL_6", "COMPONENT_SHORTARM_SIGHT_MATERIAL_8", "COMPONENT_SHORTARM_SIGHT_MATERIAL_9", "COMPONENT_SHORTARM_SIGHT_MATERIAL_7", "COMPONENT_SHORTARM_SIGHT_MATERIAL_10" }
local SHARED_SHORTARM_TRIGGER_MATERIAL <const> = { "COMPONENT_SHORTARM_TRIGGER_MATERIAL_1", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_2", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_3", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_4", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_5", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_6", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_8", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_9", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_7", "COMPONENT_SHORTARM_TRIGGER_MATERIAL_10" }
local SHARED_SHORTARM_FULL_ENGRAVING <const> = { "COMPONENT_SHORTARM_FULL_ENGRAVING_NONE", "COMPONENT_SHORTARM_ENGRAVING_1", "COMPONENT_SHORTARM_ENGRAVING_2", "COMPONENT_SHORTARM_ENGRAVING_3", "COMPONENT_SHORTARM_ENGRAVING_4" }
local SHARED_SHORTARM_ENGRAVING_MATERIAL <const> = { "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_1", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_2", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_3", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_4", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_5", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_6", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_8", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_9", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_7", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_10", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_11", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_12", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_13", "COMPONENT_SHORTARM_ENGRAVING_MATERIAL_14" }
local SHARED_SHORTARM_BARREL_ENGRAVING <const> = { "COMPONENT_SHORTARM_BARREL_ENGRAVING_NONE", "COMPONENT_SHORTARM_BARREL_ENGRAVING_1", "COMPONENT_SHORTARM_BARREL_ENGRAVING_2", "COMPONENT_SHORTARM_BARREL_ENGRAVING_3", "COMPONENT_SHORTARM_BARREL_ENGRAVING_4" }
local SHARED_SHORTARM_CYLINDER_ENGRAVING <const> = { "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_NONE", "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_1", "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_2", "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_3", "COMPONENT_SHORTARM_CYLINDER_ENGRAVING_4" }
local SHARED_SHORTARM_FRAME_ENGRAVING <const> = { "COMPONENT_SHORTARM_FRAME_ENGRAVING_NONE", "COMPONENT_SHORTARM_FRAME_ENGRAVING_1", "COMPONENT_SHORTARM_FRAME_ENGRAVING_2", "COMPONENT_SHORTARM_FRAME_ENGRAVING_3", "COMPONENT_SHORTARM_FRAME_ENGRAVING_4" }
local SHARED_SHORTARM_GRIPSTOCK_ENGRAVING <const> = { "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_NONE", "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_1", "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_2", "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_3", "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_4", "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_5", "COMPONENT_SHORTARM_GRIPSTOCK_ENGRAVING_6" }
local SHARED_SHORTARM_GRIPSTOCK_TINT <const> = { "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_1", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_2", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_3", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_4", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_5", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_6", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_7", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_A_8", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_1", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_2", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_3", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_4", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_5", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_6", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_7", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_B_8", "COMPONENT_SHORTARM_GRIPSTOCK_TINT_GRAY_BIRCH" }

-- Shared shotgun components, shared meaning the majority of the weapons use these
local SHARED_SHOTGUN_FULL_ENGRAVING <const> = { "COMPONENT_SHOTGUN_FULL_ENGRAVING_NONE", "COMPONENT_SHOTGUN_ENGRAVING_1", "COMPONENT_SHOTGUN_ENGRAVING_2", "COMPONENT_SHOTGUN_ENGRAVING_3", "COMPONENT_SHOTGUN_ENGRAVING_4" }
local SHARED_SHOTGUN_BARREL_ENGRAVING <const> = { "COMPONENT_SHOTGUN_BARREL_ENGRAVING_NONE", "COMPONENT_SHOTGUN_BARREL_ENGRAVING_1", "COMPONENT_SHOTGUN_BARREL_ENGRAVING_2", "COMPONENT_SHOTGUN_BARREL_ENGRAVING_3", "COMPONENT_SHOTGUN_BARREL_ENGRAVING_4" }
local SHARED_SHOTGUN_FRAME_ENGRAVING <const> = { "COMPONENT_SHOTGUN_FRAME_ENGRAVING_NONE", "COMPONENT_SHOTGUN_FRAME_ENGRAVING_1", "COMPONENT_SHOTGUN_FRAME_ENGRAVING_2", "COMPONENT_SHOTGUN_FRAME_ENGRAVING_3", "COMPONENT_SHOTGUN_FRAME_ENGRAVING_4" }
local SHARED_SHOTGUN_CYLINDER_ENGRAVING <const> = { "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_NONE", "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_1", "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_2", "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_3", "COMPONENT_SHOTGUN_CYLINDER_ENGRAVING_4" }

-- Shared ammo types, shared meaning the majority of the weapons use these
local SHARED_AMMO_PISTOL <const> = { "AMMO_PISTOL", "AMMO_PISTOL_EXPRESS", "AMMO_PISTOL_HIGH_VELOCITY" }
local SHARED_AMMO_REPEATER <const> = { "AMMO_REPEATER", "AMMO_REPEATER_EXPRESS", "AMMO_REPEATER_HIGH_VELOCITY" }
local SHARED_AMMO_REVOLVER <const> = { "AMMO_REVOLVER", "AMMO_REVOLVER_EXPRESS", "AMMO_REVOLVER_HIGH_VELOCITY" }
local SHARED_AMMO_RIFLE <const> = { "AMMO_RIFLE", "AMMO_RIFLE_EXPRESS", "AMMO_RIFLE_HIGH_VELOCITY" }
local SHARED_AMMO_SHOTGUN <const> = { "AMMO_SHOTGUN", "AMMO_SHOTGUN_SLUG" }

-- List of components for each modifiable weapon
local WEAPON_COMPONENTS <const> = {
    WEAPON_RIFLE_VARMINT = {
        AMMO = { "AMMO_22", "AMMO_22_TRANQUILIZER" },
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_VARMINT_WRAP2", "COMPONENT_RIFLE_VARMINT_WRAP3", "COMPONENT_RIFLE_VARMINT_WRAP4", "COMPONENT_RIFLE_VARMINT_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_LONGARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_VARMINT_WRAP1", "COMPONENT_RIFLE_VARMINT_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02", "COMPONENT_RIFLE_SCOPE03" },
        SIGHT = { "COMPONENT_REPEATER_PUMPACTION_SIGHT_NARROW", "COMPONENT_REPEATER_PUMPACTION_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_RIFLE_VARMINT_GRIP", "COMPONENT_RIFLE_VARMINT_GRIP_IRONWOOD", "COMPONENT_RIFLE_VARMINT_GRIP_ENGRAVED", "COMPONENT_RIFLE_VARMINT_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_SNIPERRIFLE_ROLLINGBLOCK = {
        AMMO = SHARED_AMMO_RIFLE,
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP2", "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP3", "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP4", "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_LONGARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP1", "COMPONENT_RIFLE_ROLLINGBLOCK_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02", "COMPONENT_RIFLE_SCOPE03", "COMPONENT_RIFLE_SCOPE04" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP", "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP_IRONWOOD", "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP_ENGRAVED", "COMPONENT_SNIPERRIFLE_ROLLINGBLOCK_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_RIFLE_ELEPHANT = {
        AMMO = { "AMMO_RIFLE_ELEPHANT" },
        BARREL = { "COMPONENT_RIFLE_ELEPHANT_BARREL_SHORT", "COMPONENT_RIFLE_ELEPHANT_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_ELEPHANT_WRAP2", "COMPONENT_RIFLE_ELEPHANT_WRAP3", "COMPONENT_RIFLE_ELEPHANT_WRAP4", "COMPONENT_RIFLE_ELEPHANT_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_ELEPHANT_WRAP1", "COMPONENT_RIFLE_ELEPHANT_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SIGHT = { "COMPONENT_RIFLE_ELEPHANT_SIGHT_NARROW", "COMPONENT_RIFLE_ELEPHANT_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_RIFLE_ELEPHANT_GRIP", "COMPONENT_RIFLE_ELEPHANT_GRIP_IRONWOOD", "COMPONENT_RIFLE_ELEPHANT_GRIP_ENGRAVED", "COMPONENT_RIFLE_ELEPHANT_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_SNIPERRIFLE_CARCANO = {
        AMMO = SHARED_AMMO_RIFLE,
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_CARCANO_WRAP2", "COMPONENT_RIFLE_CARCANO_WRAP3", "COMPONENT_RIFLE_CARCANO_WRAP4", "COMPONENT_RIFLE_CARCANO_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_CARCANO_WRAP1", "COMPONENT_RIFLE_CARCANO_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02", "COMPONENT_RIFLE_SCOPE03", "COMPONENT_RIFLE_SCOPE04" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_RIFLE_CARCANO_GRIP", "COMPONENT_RIFLE_CARCANO_GRIP_IRONWOOD", "COMPONENT_RIFLE_CARCANO_GRIP_ENGRAVED", "COMPONENT_RIFLE_CARCANO_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_REPEATER_HENRY = {
        AMMO = SHARED_AMMO_REPEATER,
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_REPEATER_HENRY_WRAP2", "COMPONENT_REPEATER_HENRY_WRAP3", "COMPONENT_REPEATER_HENRY_WRAP4", "COMPONENT_REPEATER_HENRY_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_LONGARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_REPEATER_HENRY_WRAP1", "COMPONENT_REPEATER_HENRY_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02" },
        SIGHT = { "COMPONENT_REPEATER_HENRY_SIGHT_NARROW", "COMPONENT_REPEATER_HENRY_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_REPEATER_HENRY_GRIP", "COMPONENT_REPEATER_HENRY_GRIP_IRONWOOD", "COMPONENT_REPEATER_HENRY_GRIP_ENGRAVED", "COMPONENT_REPEATER_HENRY_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_REVOLVER_LEMAT = {
        AMMO = { "AMMO_REVOLVER", "AMMO_REVOLVER_EXPRESS", "AMMO_REVOLVER_HIGH_VELOCITY", "AMMO_SHOTGUN" },
        BARREL = { "COMPONENT_REVOLVER_LEMAT_BARREL_SHORT", "COMPONENT_REVOLVER_LEMAT_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        CYLINDER_ENGRAVING = SHARED_SHORTARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_SHORTARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_REVOLVER_LEMAT_GRIP", "COMPONENT_REVOLVER_LEMAT_GRIP_IRONWOOD", "COMPONENT_REVOLVER_LEMAT_GRIP_EBONY", "COMPONENT_REVOLVER_LEMAT_GRIP_PEARL", "COMPONENT_REVOLVER_LEMAT_GRIP_BURLED" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_SHORTARM_HAMMER_MATERIAL,
        SIGHT = { "COMPONENT_REVOLVER_LEMAT_SIGHT_NARROW", "COMPONENT_REVOLVER_LEMAT_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_SHOTGUN_PUMP = {
        AMMO = SHARED_AMMO_SHOTGUN,
        BARREL = { "COMPONENT_SHOTGUN_PUMP_BARREL_SHORT", "COMPONENT_SHOTGUN_PUMP_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHOTGUN_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_PUMP_WRAP2", "COMPONENT_SHOTGUN_PUMP_WRAP3", "COMPONENT_SHOTGUN_PUMP_WRAP4", "COMPONENT_SHOTGUN_PUMP_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHOTGUN_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHOTGUN_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_PUMP_WRAP1", "COMPONENT_SHOTGUN_PUMP_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SIGHT = { "COMPONENT_SHOTGUN_PUMP_SIGHT_NARROW", "COMPONENT_SHOTGUN_PUMP_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_SHOTGUN_PUMP_GRIP", "COMPONENT_SHOTGUN_PUMP_GRIP_IRONWOOD", "COMPONENT_SHOTGUN_PUMP_GRIP_ENGRAVED", "COMPONENT_SHOTGUN_PUMP_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_PISTOL_MAUSER = {
        AMMO = SHARED_AMMO_PISTOL,
        BARREL = { "COMPONENT_PISTOL_MAUSER_BARREL_SHORT", "COMPONENT_PISTOL_MAUSER_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        CYLINDER_MATERIAL = SHARED_SHORTARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_PISTOL_MAUSER_GRIP", "COMPONENT_PISTOL_MAUSER_GRIP_IRONWOOD", "COMPONENT_PISTOL_MAUSER_GRIP_EBONY", "COMPONENT_PISTOL_MAUSER_GRIP_PEARL", "COMPONENT_PISTOL_MAUSER_GRIP_BURLED" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_SHORTARM_HAMMER_MATERIAL,
        SIGHT = { "COMPONENT_PISTOL_MAUSER_SIGHT_NARROW", "COMPONENT_PISTOL_MAUSER_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_SHOTGUN_SAWEDOFF = {
        AMMO = SHARED_AMMO_SHOTGUN,
        BARREL_ENGRAVING = SHARED_SHOTGUN_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_SAWEDOFF_WRAP2", "COMPONENT_SHOTGUN_SAWEDOFF_WRAP3", "COMPONENT_SHOTGUN_SAWEDOFF_WRAP4", "COMPONENT_SHOTGUN_SAWEDOFF_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_SHOTGUN_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHOTGUN_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHOTGUN_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_SAWEDOFF_WRAP1" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SIGHT = { "COMPONENT_SHOTGUN_SAWED_SIGHT_NARROW", "COMPONENT_SHOTGUN_SAWED_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_SHOTGUN_SAWEDOFF_GRIP", "COMPONENT_SHOTGUN_SAWEDOFF_GRIP_IRONWOOD", "COMPONENT_SHOTGUN_SAWEDOFF_GRIP_EBONY", "COMPONENT_SHOTGUN_SAWEDOFF_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_REVOLVER_CATTLEMAN = {
        AMMO = SHARED_AMMO_REVOLVER,
        BARREL = { "COMPONENT_REVOLVER_CATTLEMAN_BARREL_SHORT", "COMPONENT_REVOLVER_CATTLEMAN_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        CYLINDER_ENGRAVING = SHARED_SHORTARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_SHORTARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_REVOLVER_CATTLEMAN_GRIP", "COMPONENT_REVOLVER_CATTLEMAN_GRIP_IRONWOOD", "COMPONENT_REVOLVER_CATTLEMAN_GRIP_EBONY", "COMPONENT_REVOLVER_CATTLEMAN_GRIP_PEARL", "COMPONENT_REVOLVER_CATTLEMAN_GRIP_GOOD_HONOR", "COMPONENT_REVOLVER_CATTLEMAN_GRIP_BURLED" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_SHORTARM_HAMMER_MATERIAL,
        SIGHT = { "COMPONENT_REVOLVER_CATTLEMAN_SIGHT_NARROW", "COMPONENT_REVOLVER_CATTLEMAN_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_BOW_IMPROVED = {
        AMMO = { "AMMO_ARROW" },
        FRAME_TINT = { "COMPONENT_BOW_FRAME_TINT_A_1", "COMPONENT_BOW_FRAME_TINT_A_2", "COMPONENT_BOW_FRAME_TINT_A_3", "COMPONENT_BOW_FRAME_TINT_A_4", "COMPONENT_BOW_FRAME_TINT_A_5", "COMPONENT_BOW_FRAME_TINT_A_6", "COMPONENT_BOW_FRAME_TINT_A_7", "COMPONENT_BOW_FRAME_TINT_A_8" },
        GRIPSTOCK_TINT = { "COMPONENT_BOW_GRIPSTOCK_TINT_A_1", "COMPONENT_BOW_GRIPSTOCK_TINT_A_2", "COMPONENT_BOW_GRIPSTOCK_TINT_A_3", "COMPONENT_BOW_GRIPSTOCK_TINT_A_4", "COMPONENT_BOW_GRIPSTOCK_TINT_A_5", "COMPONENT_BOW_GRIPSTOCK_TINT_A_6", "COMPONENT_BOW_GRIPSTOCK_TINT_A_7", "COMPONENT_BOW_GRIPSTOCK_TINT_A_8" },
        TRIGGER_TINT = { "COMPONENT_BOW_TRIGGER_TINT_A_1", "COMPONENT_BOW_TRIGGER_TINT_A_2", "COMPONENT_BOW_TRIGGER_TINT_A_3", "COMPONENT_BOW_TRIGGER_TINT_A_4", "COMPONENT_BOW_TRIGGER_TINT_A_5", "COMPONENT_BOW_TRIGGER_TINT_A_6", "COMPONENT_BOW_TRIGGER_TINT_A_7", "COMPONENT_BOW_TRIGGER_TINT_A_8" },
    },
    WEAPON_REPEATER_EVANS = {
        AMMO = SHARED_AMMO_REPEATER,
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_REPEATER_EVANS_WRAP2", "COMPONENT_REPEATER_EVANS_WRAP3", "COMPONENT_REPEATER_EVANS_WRAP4", "COMPONENT_REPEATER_EVANS_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_LONGARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_REPEATER_EVANS_WRAP", "COMPONENT_REPEATER_EVANS_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02" },
        SIGHT = { "COMPONENT_REPEATER_EVANS_SIGHT_NARROW", "COMPONENT_REPEATER_EVANS_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_REPEATER_EVANS_GRIP", "COMPONENT_REPEATER_EVANS_GRIP_IRONWOOD", "COMPONENT_REPEATER_EVANS_GRIP_ENGRAVED", "COMPONENT_REPEATER_EVANS_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_SHOTGUN_DOUBLEBARREL = {
        AMMO = SHARED_AMMO_SHOTGUN,
        BARREL = { "COMPONENT_SHOTGUN_DOUBLEBARREL_BARREL_SHORT", "COMPONENT_SHOTGUN_DOUBLEBARREL_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHOTGUN_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP2", "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP3", "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP4", "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_SHOTGUN_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHOTGUN_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHOTGUN_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP1", "COMPONENT_SHOTGUN_DOUBLEBARREL_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SIGHT = { "COMPONENT_SHOTGUN_DOUBLEBARREL_SIGHT_NARROW", "COMPONENT_SHOTGUN_DOUBLEBARREL_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP", "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP_IRONWOOD", "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP_ENGRAVED", "COMPONENT_SHOTGUN_DOUBLEBARREL_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_REVOLVER_NAVY = {
        AMMO = SHARED_AMMO_REVOLVER,
        BARREL = { "COMPONENT_REVOLVER_NAVY_BARREL_SHORT", "COMPONENT_REVOLVER_NAVY_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        CYLINDER_ENGRAVING = SHARED_SHORTARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_SHORTARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_REVOLVER_NAVY_GRIP", "COMPONENT_REVOLVER_NAVY_GRIP_IRONWOOD", "COMPONENT_REVOLVER_NAVY_GRIP_EBONY", "COMPONENT_REVOLVER_NAVY_GRIP_PEARL", "COMPONENT_REVOLVER_NAVY_GRIP_BURLED" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_SHORTARM_HAMMER_MATERIAL,
        SIGHT = { "COMPONENT_REVOLVER_NAVY_SIGHT_NARROW", "COMPONENT_REVOLVER_NAVY_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_REPEATER_WINCHESTER = {
        AMMO = SHARED_AMMO_REPEATER,
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_REPEATER_WINCHESTER_WRAP2", "COMPONENT_REPEATER_WINCHESTER_WRAP3", "COMPONENT_REPEATER_WINCHESTER_WRAP4", "COMPONENT_REPEATER_WINCHESTER_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_LONGARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_REPEATER_WINCHESTER_WRAP1", "COMPONENT_REPEATER_WINCHESTER_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02" },
        SIGHT = { "COMPONENT_REPEATER_WINCHESTER_SIGHT_NARROW", "COMPONENT_REPEATER_WINCHESTER_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_REPEATER_WINCHESTER_GRIP", "COMPONENT_REPEATER_WINCHESTER_GRIP_IRONWOOD", "COMPONENT_REPEATER_WINCHESTER_GRIP_ENGRAVED", "COMPONENT_REPEATER_WINCHESTER_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_RIFLE_SPRINGFIELD = {
        AMMO = SHARED_AMMO_RIFLE,
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_SPRINGFIELD_WRAP2", "COMPONENT_RIFLE_SPRINGFIELD_WRAP3", "COMPONENT_RIFLE_SPRINGFIELD_WRAP4", "COMPONENT_RIFLE_SPRINGFIELD_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_LONGARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_SPRINGFIELD_WRAP1", "COMPONENT_RIFLE_SPRINGFIELD_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02", "COMPONENT_RIFLE_SCOPE03" },
        SIGHT = { "COMPONENT_RIFLE_SPRINGFIELD_SIGHT_NARROW", "COMPONENT_RIFLE_SPRINGFIELD_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_RIFLE_SPRINGFIELD_GRIP", "COMPONENT_RIFLE_SPRINGFIELD_GRIP_IRONWOOD", "COMPONENT_RIFLE_SPRINGFIELD_GRIP_ENGRAVED", "COMPONENT_RIFLE_SPRINGFIELD_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_SHOTGUN_REPEATING = {
        AMMO = SHARED_AMMO_SHOTGUN,
        BARREL = { "COMPONENT_SHOTGUN_REPEATING_BARREL_SHORT", "COMPONENT_SHOTGUN_REPEATING_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHOTGUN_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_REPEATING01_WRAP2", "COMPONENT_SHOTGUN_REPEATING_WRAP3", "COMPONENT_SHOTGUN_REPEATING_WRAP4", "COMPONENT_SHOTGUN_REPEATING_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_SHOTGUN_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHOTGUN_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHOTGUN_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_REPEATING01_WRAP1", "COMPONENT_SHOTGUN_REPEATING_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SIGHT = { "COMPONENT_SHOTGUN_REPEATING_SIGHT_NARROW", "COMPONENT_SHOTGUN_REPEATING_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_SHOTGUN_REPEATING01_GRIP", "COMPONENT_SHOTGUN_REPEATING01_GRIP_IRONWOOD", "COMPONENT_SHOTGUN_REPEATING01_GRIP_ENGRAVED", "COMPONENT_SHOTGUN_REPEATING_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_SHOTGUN_SEMIAUTO = {
        AMMO = SHARED_AMMO_SHOTGUN,
        BARREL = { "COMPONENT_SHOTGUN_SEMIAUTO_BARREL_SHORT", "COMPONENT_SHOTGUN_SEMIAUTO_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHOTGUN_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_SEMIAUTO_WRAP2", "COMPONENT_SHOTGUN_SEMIAUTO_WRAP3", "COMPONENT_SHOTGUN_SEMIAUTO_WRAP4", "COMPONENT_SHOTGUN_SEMIAUTO_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHOTGUN_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHOTGUN_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_SHOTGUN_SEMIAUTO_WRAP1", "COMPONENT_SHOTGUN_SEMIAUTO_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SIGHT = { "COMPONENT_SHOTGUN_SEMIAUTO_SIGHT_NARROW", "COMPONENT_SHOTGUN_SEMIAUTO_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_SHOTGUN_SEMIAUTO_GRIP", "COMPONENT_SHOTGUN_SEMIAUTO_GRIP_IRONWOOD", "COMPONENT_SHOTGUN_SEMIAUTO_GRIP_ENGRAVED", "COMPONENT_SHOTGUN_SEMIAUTO_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_RIFLE_BOLTACTION = {
        AMMO = SHARED_AMMO_RIFLE,
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_BOLTACTION_WRAP2", "COMPONENT_RIFLE_BOLTACTION_WRAP3", "COMPONENT_RIFLE_BOLTACTION_WRAP4", "COMPONENT_RIFLE_BOLTACTION_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_RIFLE_BOLTACTION_WRAP", "COMPONENT_RIFLE_BOLTACTION_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02", "COMPONENT_RIFLE_SCOPE03" },
        SIGHT = { "COMPONENT_RIFLE_BOLTACTION_SIGHT_NARROW", "COMPONENT_RIFLE_BOLTACTION_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_RIFLE_BOLTACTION_GRIP", "COMPONENT_RIFLE_BOLTACTION_GRIP_IRONWOOD", "COMPONENT_RIFLE_BOLTACTION_GRIP_ENGRAVED", "COMPONENT_RIFLE_BOLTACTION_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_PISTOL_M1899 = {
        AMMO = SHARED_AMMO_PISTOL,
        BARREL = { "COMPONENT_PISTOL_M1899_BARREL_SHORT", "COMPONENT_PISTOL_M1899_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_PISTOL_M1899_GRIP", "COMPONENT_PISTOL_M1899_GRIP_IRONWOOD", "COMPONENT_PISTOL_M1899_GRIP_EBONY", "COMPONENT_PISTOL_M1899_GRIP_PEARL" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        SIGHT = { "COMPONENT_PISTOL_M1899_SIGHT_NARROW", "COMPONENT_PISTOL_M1899_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_PISTOL_VOLCANIC = {
        AMMO = SHARED_AMMO_PISTOL,
        BARREL = { "COMPONENT_PISTOL_VOLCANIC_BARREL_SHORT", "COMPONENT_PISTOL_VOLCANIC_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        CYLINDER_ENGRAVING = SHARED_SHORTARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_SHORTARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_PISTOL_VOLCANIC_GRIP", "COMPONENT_PISTOL_VOLCANIC_GRIP_IRONWOOD", "COMPONENT_PISTOL_VOLCANIC_GRIP_EBONY", "COMPONENT_PISTOL_VOLCANIC_GRIP_PEARL", "COMPONENT_PISTOL_VOLCANIC_GRIP_BURLED" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_SHORTARM_HAMMER_MATERIAL,
        SIGHT = { "COMPONENT_PISTOL_VOLCANIC_SIGHT_NARROW", "COMPONENT_PISTOL_VOLCANIC_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_PISTOL_SEMIAUTO = {
        AMMO = SHARED_AMMO_PISTOL,
        BARREL = { "COMPONENT_PISTOL_SEMIAUTO_BARREL_SHORT", "COMPONENT_PISTOL_SEMIAUTO_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        CYLINDER_ENGRAVING = SHARED_SHORTARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_SHORTARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_PISTOL_SEMIAUTO_GRIP", "COMPONENT_PISTOL_SEMIAUTO_GRIP_IRONWOOD", "COMPONENT_PISTOL_SEMIAUTO_GRIP_EBONY", "COMPONENT_PISTOL_SEMIAUTO_GRIP_PEARL", "COMPONENT_PISTOL_SEMIAUTO_GRIP_BURLED" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        SIGHT = { "COMPONENT_PISTOL_SEMIAUTO_SIGHT_NARROW", "COMPONENT_PISTOL_SEMIAUTO_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_REVOLVER_DOUBLEACTION = {
        AMMO = SHARED_AMMO_REVOLVER,
        BARREL = { "COMPONENT_REVOLVER_DOUBLEACTION_BARREL_SHORT", "COMPONENT_REVOLVER_DOUBLEACTION_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        CYLINDER_ENGRAVING = SHARED_SHORTARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_SHORTARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_REVOLVER_DOUBLEACTION_GRIP", "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_IRONWOOD", "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_EBONY", "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_PEARL", "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_BAD_HONOR", "COMPONENT_REVOLVER_DOUBLEACTION_GRIP_BURLED" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_SHORTARM_HAMMER_MATERIAL,
        SIGHT = { "COMPONENT_REVOLVER_DOUBLEACTION_SIGHT_NARROW", "COMPONENT_REVOLVER_DOUBLEACTION_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_REVOLVER_SCHOFIELD = {
        AMMO = SHARED_AMMO_REVOLVER,
        BARREL = { "COMPONENT_REVOLVER_SCHOFIELD_BARREL_SHORT", "COMPONENT_REVOLVER_SCHOFIELD_BARREL_LONG" },
        BARREL_ENGRAVING = SHARED_SHORTARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_SHORTARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_SHORTARM_BARREL_RIFLING,
        CYLINDER_ENGRAVING = SHARED_SHORTARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_SHORTARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_SHORTARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_SHORTARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_SHORTARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_SHORTARM_FULL_ENGRAVING,
        GRIP = { "COMPONENT_REVOLVER_SCHOFIELD_GRIP", "COMPONENT_REVOLVER_SCHOFIELD_GRIP_IRONWOOD", "COMPONENT_REVOLVER_SCHOFIELD_GRIP_EBONY", "COMPONENT_REVOLVER_SCHOFIELD_GRIP_PEARL", "COMPONENT_REVOLVER_SCHOFIELD_GRIP_BURLED" },
        GRIPSTOCK_ENGRAVING = SHARED_SHORTARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_SHORTARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_SHORTARM_HAMMER_MATERIAL,
        SIGHT = { "COMPONENT_REVOLVER_SCHOFIELD_SIGHT_NARROW", "COMPONENT_REVOLVER_SCHOFIELD_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_SHORTARM_SIGHT_MATERIAL,
        TRIGGER_MATERIAL = SHARED_SHORTARM_TRIGGER_MATERIAL,
    },
    WEAPON_REPEATER_CARBINE = {
        AMMO = SHARED_AMMO_REPEATER,
        BARREL_ENGRAVING = SHARED_LONGARM_BARREL_ENGRAVING,
        BARREL_MATERIAL = SHARED_LONGARM_BARREL_MATERIAL,
        BARREL_RIFLING = SHARED_LONGARM_BARREL_RIFLING,
        CLOTH_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_REPEATER_CARBINE_WRAP2", "COMPONENT_REPEATER_CARBINE_WRAP3", "COMPONENT_REPEATER_CARBINE_WRAP4", "COMPONENT_REPEATER_CARBINE_WRAP5" },
        CLOTH_WRAP_TINT = SHARED_LONGARM_CLOTH_WRAP_TINT,
        CYLINDER_ENGRAVING = SHARED_LONGARM_CYLINDER_ENGRAVING,
        CYLINDER_MATERIAL = SHARED_LONGARM_CYLINDER_MATERIAL,
        ENGRAVING_MATERIAL = SHARED_LONGARM_ENGRAVING_MATERIAL,
        FRAME_ENGRAVING = SHARED_LONGARM_FRAME_ENGRAVING,
        FRAME_MATERIAL = SHARED_LONGARM_FRAME_MATERIAL,
        FULL_ENGRAVING = SHARED_LONGARM_FULL_ENGRAVING,
        GRIPSTOCK_ENGRAVING = SHARED_LONGARM_GRIPSTOCK_ENGRAVING,
        GRIPSTOCK_TINT = SHARED_LONGARM_GRIPSTOCK_TINT,
        HAMMER_MATERIAL = SHARED_LONGARM_HAMMER_MATERIAL,
        LEATHER_WRAP = { "COMPONENT_WRAP_NONE", "COMPONENT_REPEATER_CARBINE_WRAP1", "COMPONENT_REPEATER_CARBINE_WRAP6" },
        LEATHER_WRAP_TINT = SHARED_LONGARM_LEATHER_WRAP_TINT,
        SCOPE = { "COMPONENT_SCOPE_NONE", "COMPONENT_RIFLE_SCOPE02" },
        SIGHT = { "COMPONENT_REPEATER_CARBINE_SIGHT_NARROW", "COMPONENT_REPEATER_CARBINE_SIGHT_WIDE" },
        SIGHT_MATERIAL = SHARED_LONGARM_SIGHT_MATERIAL,
        STOCK = { "COMPONENT_REPEATER_CARBINE_GRIP", "COMPONENT_REPEATER_CARBINE_GRIP_IRONWOOD", "COMPONENT_REPEATER_CARBINE_GRIP_ENGRAVED", "COMPONENT_REPEATER_CARBINE_GRIP_BURLED" },
        TRIGGER_MATERIAL = SHARED_LONGARM_TRIGGER_MATERIAL,
    },
    WEAPON_MELEE_KNIFE = {
        BLADE_ENGRAVING = { "COMPONENT_MELEE_BLADE_ENGRAVING_NONE", "COMPONENT_MELEE_BLADE_ENGRAVING_1", "COMPONENT_MELEE_BLADE_ENGRAVING_2", "COMPONENT_MELEE_BLADE_ENGRAVING_3" },
        BLADE_MATERIAL = { "COMPONENT_MELEE_BLADE_MATERIAL_1", "COMPONENT_MELEE_BLADE_MATERIAL_2", "COMPONENT_MELEE_BLADE_MATERIAL_3", "COMPONENT_MELEE_BLADE_MATERIAL_4", "COMPONENT_MELEE_BLADE_MATERIAL_5", "COMPONENT_MELEE_BLADE_MATERIAL_6", "COMPONENT_MELEE_BLADE_MATERIAL_8", "COMPONENT_MELEE_BLADE_MATERIAL_9", "COMPONENT_MELEE_BLADE_MATERIAL_7" },
        ENGRAVING_MATERIAL = { "COMPONENT_MELEE_ENGRAVING_MATERIAL_1", "COMPONENT_MELEE_ENGRAVING_MATERIAL_2", "COMPONENT_MELEE_ENGRAVING_MATERIAL_3", "COMPONENT_MELEE_ENGRAVING_MATERIAL_4", "COMPONENT_MELEE_ENGRAVING_MATERIAL_5", "COMPONENT_MELEE_ENGRAVING_MATERIAL_6", "COMPONENT_MELEE_ENGRAVING_MATERIAL_8", "COMPONENT_MELEE_ENGRAVING_MATERIAL_9", "COMPONENT_MELEE_ENGRAVING_MATERIAL_7", "COMPONENT_MELEE_ENGRAVING_MATERIAL_11", "COMPONENT_MELEE_ENGRAVING_MATERIAL_12", "COMPONENT_MELEE_ENGRAVING_MATERIAL_13", "COMPONENT_MELEE_ENGRAVING_MATERIAL_14" },
        FULL_ENGRAVING = { "COMPONENT_MELEE_FULL_ENGRAVING_NONE", "COMPONENT_MELEE_ENGRAVING_1", "COMPONENT_MELEE_ENGRAVING_2", "COMPONENT_MELEE_ENGRAVING_3" },
        GRIPSTOCK_TINT = { "COMPONENT_MELEE_GRIP_TINT_A_1", "COMPONENT_MELEE_GRIP_TINT_A_2", "COMPONENT_MELEE_GRIP_TINT_A_3", "COMPONENT_MELEE_GRIP_TINT_A_4", "COMPONENT_MELEE_GRIP_TINT_A_5", "COMPONENT_MELEE_GRIP_TINT_A_6", "COMPONENT_MELEE_GRIP_TINT_A_7", "COMPONENT_MELEE_GRIP_TINT_A_8", "COMPONENT_MELEE_GRIP_TINT_B_1", "COMPONENT_MELEE_GRIP_TINT_B_2", "COMPONENT_MELEE_GRIP_TINT_B_3", "COMPONENT_MELEE_GRIP_TINT_B_4", "COMPONENT_MELEE_GRIP_TINT_B_5", "COMPONENT_MELEE_GRIP_TINT_B_6", "COMPONENT_MELEE_GRIP_TINT_B_7", "COMPONENT_MELEE_GRIP_TINT_B_8", "COMPONENT_MELEE_GRIP_TINT_GRAY_BIRCH" }
    }
}

_G.GetWeaponStats = getWeaponStats
_G.MODIFIABLE_WEAPONS = MODIFIABLE_WEAPONS
_G.WEAPON_COMPONENTS = WEAPON_COMPONENTS
