local INVENTORY_DEMO = {
    { Id = 1,  Active = true,  Nickname = "Horsey McHorseface", Horse = "A_C_HORSE_ARABIAN_REDCHESTNUT" },
    { Id = 2,  Active = false, Nickname = "Horse with No Name", Horse = "A_C_HORSE_THOROUGHBRED_BLOODBAY" },
    { Id = 3,  Active = false, Nickname = nil,                  Horse = nil },
    { Id = 4,  Active = false, Nickname = nil,                  Horse = nil },
    { Id = 5,  Active = false, Nickname = nil,                  Horse = nil },
    { Id = 6,  Active = false, Nickname = nil,                  Horse = nil },
    { Id = 7,  Active = false, Nickname = nil,                  Horse = nil },
    { Id = 8,  Active = false, Nickname = nil,                  Horse = nil },
    { Id = 9,  Active = false, Nickname = nil,                  Horse = nil },
    { Id = 10, Active = false, Nickname = nil,                  Horse = nil },
}

local HORSES <const> = {
    {
        Class = "HORSE_CLASS_RIDING",
        Items = {
            {
                Model = "A_C_HORSE_KENTUCKYSADDLE_BLACK",
                Catalog = "HORSE_BREED_KENTUCKYSADDLE_BLACK",
                BreedShort = "BREED_KENTUCKYSADDLE",
                BreedFull = "BREED_KENTUCKYSADDLE_BLACK",
                Coat = "COAT_BLACK",
            },
            {
                Model = "A_C_HORSE_KENTUCKYSADDLE_CHESTNUTPINTO",
                Catalog = "HORSE_BREED_KENTUCKYSADDLE_CHESTNUTPINTO",
                BreedShort = "BREED_KENTUCKYSADDLE",
                BreedFull = "BREED_KENTUCKYSADDLE_CHESTNUTPINTO",
                Coat = "COAT_CHPIN",
            },
            {
                Model = "A_C_HORSE_KENTUCKYSADDLE_GREY",
                Catalog = "HORSE_BREED_KENTUCKYSADDLE_GREY",
                BreedShort = "BREED_KENTUCKYSADDLE",
                BreedFull = "BREED_KENTUCKYSADDLE_GREY",
                Coat = "COAT_GREY",
            },
            {
                Model = "A_C_HORSE_KENTUCKYSADDLE_SILVERBAY",
                Catalog = "HORSE_BREED_KENTUCKYSADDLE_SILVERBAY",
                BreedShort = "BREED_KENTUCKYSADDLE",
                BreedFull = "BREED_KENTUCKYSADDLE_SILVERBAY",
                Coat = "COAT_SILVERBAY",
            },
            {
                Model = "A_C_HORSE_MORGAN_BAY",
                Catalog = "HORSE_BREED_MORGAN_BAY",
                BreedShort = "BREED_MORGAN",
                BreedFull = "BREED_MORGAN_BAY",
                Coat = "COAT_BAY",
            },
            {
                Model = "A_C_HORSE_MORGAN_BAYROAN",
                Catalog = "HORSE_BREED_MORGAN_BAYROAN",
                BreedShort = "BREED_MORGAN",
                BreedFull = "BREED_MORGAN_BAYROAN",
                Coat = "COAT_BAYR",
            },
            {
                Model = "A_C_HORSE_MORGAN_FLAXENCHESTNUT",
                Catalog = "HORSE_BREED_MORGAN_FLAXENCHESTNUT",
                BreedShort = "BREED_MORGAN",
                BreedFull = "BREED_MORGAN_FLAXENCHESTNUT",
                Coat = "COAT_FLAXCH",
            },
            {
                Model = "A_C_HORSE_MORGAN_PALOMINO",
                Catalog = "HORSE_BREED_MORGAN_PALOMINO",
                BreedShort = "BREED_MORGAN",
                BreedFull = "BREED_MORGAN_PALOMINO",
                Coat = "COAT_PAL",
            },
            {
                Model = "A_C_HORSE_TENNESSEEWALKER_BLACKRABICANO",
                Catalog = "HORSE_BREED_TENNESSEEWALKER_BLACKRABICANO",
                BreedShort = "BREED_TENNESSEEWALKER",
                BreedFull = "BREED_TENNESSEEWALKER_BLACKRABICANO",
                Coat = "COAT_BLACKRAB",
            },
            {
                Model = "A_C_HORSE_TENNESSEEWALKER_CHESTNUT",
                Catalog = "HORSE_BREED_TENNESSEEWALKER_CHESTNUT",
                BreedShort = "BREED_TENNESSEEWALKER",
                BreedFull = "BREED_TENNESSEEWALKER_CHESTNUT",
                Coat = "COAT_CH",
            },
            {
                Model = "A_C_HORSE_TENNESSEEWALKER_DAPPLEBAY",
                Catalog = "HORSE_BREED_TENNESSEEWALKER_DAPPLEBAY",
                BreedShort = "BREED_TENNESSEEWALKER",
                BreedFull = "BREED_TENNESSEEWALKER_DAPPLEBAY",
                Coat = "COAT_DAPBAY",
            },
            {
                Model = "A_C_HORSE_TENNESSEEWALKER_REDROAN",
                Catalog = "HORSE_BREED_TENNESSEEWALKER_REDROAN",
                BreedShort = "BREED_TENNESSEEWALKER",
                BreedFull = "BREED_TENNESSEEWALKER_REDROAN",
                Coat = "COAT_REDR",
            },
            {
                Model = "A_C_HORSE_TENNESSEEWALKER_FLAXENROAN",
                Catalog = "HORSE_BREED_TENNESSEEWALKER_FLAXENROAN",
                BreedShort = "BREED_TENNESSEEWALKER",
                BreedFull = "BREED_TENNESSEEWALKER_FLAXENROAN",
                Coat = "COAT_FLAXR",
            },
            {
                Model = "A_C_HORSE_MURFREEBROOD_MANGE_01",
                Catalog = "HORSE_BREED_MURFREEBROOD_MANGE_01",
                BreedShort = "BREED_TENNESSEEWALKER",
                BreedFull = "BREED_MURFREEBROOD_MANGE_01",
                Coat = "COAT_BLANKET",
            }
        }
    },
    {
        Class = "HORSE_CLASS_DRAFT",
        Items = {
            {
                Model = "A_C_HORSE_BELGIAN_BLONDCHESTNUT",
                Catalog = "HORSE_BREED_BELGIAN_BLONDCHESTNUT",
                BreedShort = "BREED_BELGIAN",
                BreedFull = "BREED_BELGIAN_BLONDCHESTNUT",
                Coat = "COAT_BLONDCH",
            },
            {
                Model = "A_C_HORSE_BELGIAN_MEALYCHESTNUT",
                Catalog = "HORSE_BREED_BELGIAN_MEALYCHESTNUT",
                BreedShort = "BREED_BELGIAN",
                BreedFull = "BREED_BELGIAN_MEALYCHESTNUT",
                Coat = "COAT_MEALYCH",
            },
            {
                Model = "A_C_HORSE_SHIRE_DARKBAY",
                Catalog = "HORSE_BREED_SHIRE_DARKBAY",
                BreedShort = "BREED_SHIRE",
                BreedFull = "BREED_SHIRE_DARKBAY",
                Coat = "COAT_DARKBAY",
            },
            {
                Model = "A_C_HORSE_SHIRE_LIGHTGREY",
                Catalog = "HORSE_BREED_SHIRE_LIGHTGREY",
                BreedShort = "BREED_SHIRE",
                BreedFull = "BREED_SHIRE_LIGHTGREY",
                Coat = "COAT_LGREY",
            },
            {
                Model = "A_C_HORSE_SUFFOLKPUNCH_SORREL",
                Catalog = "HORSE_BREED_SUFFOLKPUNCH_SORREL",
                BreedShort = "BREED_SUFFOLKPUNCH",
                BreedFull = "BREED_SUFFOLKPUNCH_SORREL",
                Coat = "COAT_SORREL",
            },
            {
                Model = "A_C_HORSE_SUFFOLKPUNCH_REDCHESTNUT",
                Catalog = "HORSE_BREED_SUFFOLKPUNCH_REDCHESTNUT",
                BreedShort = "BREED_SUFFOLKPUNCH",
                BreedFull = "BREED_SUFFOLKPUNCH_REDCHESTNUT",
                Coat = "COAT_REDCH",
            }
        }
    },
    {
        Class = "HORSE_CLASS_RACE",
        Items = {
            {
                Model = "A_C_HORSE_AMERICANSTANDARDBRED_BLACK",
                Catalog = "HORSE_BREED_AMERICANSTANDARDBRED_BLACK",
                BreedShort = "BREED_AMERICANSTANDARDBRED",
                BreedFull = "BREED_AMERICANSTANDARDBRED_BLACK",
                Coat = "COAT_BLACK",
            },
            {
                Model = "A_C_HORSE_AMERICANSTANDARDBRED_BUCKSKIN",
                Catalog = "HORSE_BREED_AMERICANSTANDARDBRED_BUCKSKIN",
                BreedShort = "BREED_AMERICANSTANDARDBRED",
                BreedFull = "BREED_AMERICANSTANDARDBRED_BUCKSKIN",
                Coat = "COAT_BUCKSKIN",
            },
            {
                Model = "A_C_HORSE_AMERICANSTANDARDBRED_PALOMINODAPPLE",
                Catalog = "HORSE_BREED_AMERICANSTANDARDBRED_PALOMINODAPPLE",
                BreedShort = "BREED_AMERICANSTANDARDBRED",
                BreedFull = "BREED_AMERICANSTANDARDBRED_PALOMINODAPPLE",
                Coat = "COAT_PALDAP",
            },
            {
                Model = "A_C_HORSE_AMERICANSTANDARDBRED_SILVERTAILBUCKSKIN",
                Catalog = "HORSE_BREED_AMERICANSTANDARDBRED_SILVERTAILBUCKSKIN",
                BreedShort = "BREED_AMERICANSTANDARDBRED",
                BreedFull = "BREED_AMERICANSTANDARDBRED_SILVERTAILBUCKSKIN",
                Coat = "COAT_SILVERTAILBUCKSKIN",
            },
            {
                Model = "A_C_HORSE_NOKOTA_BLUEROAN",
                Catalog = "HORSE_BREED_NOKOTA_BLUEROAN",
                BreedShort = "BREED_NOKOTA",
                BreedFull = "BREED_NOKOTA_BLUEROAN",
                Coat = "COAT_BLUER",
            },
            {
                Model = "A_C_HORSE_NOKOTA_WHITEROAN",
                Catalog = "HORSE_BREED_NOKOTA_WHITEROAN",
                BreedShort = "BREED_NOKOTA",
                BreedFull = "BREED_NOKOTA_WHITEROAN",
                Coat = "COAT_WHITER",
            },
            {
                Model = "A_C_HORSE_NOKOTA_REVERSEDAPPLEROAN",
                Catalog = "HORSE_BREED_NOKOTA_REVERSEDAPPLEROAN",
                BreedShort = "BREED_NOKOTA",
                BreedFull = "BREED_NOKOTA_REVERSEDAPPLEROAN",
                Coat = "COAT_REVDAPR",
            },
            {
                Model = "A_C_HORSE_THOROUGHBRED_BLOODBAY",
                Catalog = "HORSE_BREED_THOROUGHBRED_BLOODBAY",
                BreedShort = "BREED_THOROUGHBRED",
                BreedFull = "BREED_THOROUGHBRED_BLOODBAY",
                Coat = "COAT_BLBAY",
            },
            {
                Model = "A_C_HORSE_THOROUGHBRED_DAPPLEGREY",
                Catalog = "HORSE_BREED_THOROUGHBRED_DAPPLEGREY",
                BreedShort = "BREED_THOROUGHBRED",
                BreedFull = "BREED_THOROUGHBRED_DAPPLEGREY",
                Coat = "COAT_DAPGREY",
            },
            {
                Model = "A_C_HORSE_THOROUGHBRED_BRINDLE",
                Catalog = "HORSE_BREED_THOROUGHBRED_BRINDLE",
                BreedShort = "BREED_THOROUGHBRED",
                BreedFull = "BREED_THOROUGHBRED_BRINDLE",
                Coat = "COAT_BRINDLE",
            },
            {
                Model = "A_C_HORSE_THOROUGHBRED_BLACKCHESTNUT",
                Catalog = "HORSE_BREED_THOROUGHBRED_BLACKCHESTNUT",
                BreedShort = "BREED_THOROUGHBRED",
                BreedFull = "BREED_THOROUGHBRED_BLACKCHESTNUT",
                Coat = "COAT_BLACKCH",
            },
            {
                Model = "A_C_HORSE_MURFREEBROOD_MANGE_02",
                Catalog = "HORSE_BREED_MURFREEBROOD_MANGE_02",
                BreedShort = "BREED_NOKOTA",
                BreedFull = "BREED_MURFREEBROOD_MANGE_02",
                Coat = "COAT_BLUER",
            },
            {
                Model = "A_C_HORSE_THOROUGHBRED_REVERSEDAPPLEBLACK",
                Catalog = nil,
                BreedShort = "BREED_THOROUGHBRED",
                BreedFull = "BREED_THOROUGHBRED_REVERSEDAPPLEBLACK",
                Coat = "COAT_REVDAPBLACK",
            },
            {
                Model = "A_C_HORSE_AMERICANSTANDARDBRED_LIGHTBUCKSKIN",
                Catalog = nil,
                BreedShort = "BREED_AMERICANSTANDARDBRED",
                BreedFull = "BREED_AMERICANSTANDARDBRED_LIGHTBUCKSKIN",
                Coat = "COAT_LIGHTBUCKSKIN",
            }
        }
    },
    {
        Class = "HORSE_CLASS_WAR",
        Items = {
            {
                Model = "A_C_HORSE_ANDALUSIAN_DARKBAY",
                Catalog = "HORSE_BREED_ANDALUSIAN_DARKBAY",
                BreedShort = "BREED_ANDALUSIAN",
                BreedFull = "BREED_ANDALUSIAN_DARKBAY",
                Coat = "COAT_DARKBAY",
            },
            {
                Model = "A_C_HORSE_ANDALUSIAN_ROSEGRAY",
                Catalog = "HORSE_BREED_ANDALUSIAN_ROSEGRAY",
                BreedShort = "BREED_ANDALUSIAN",
                BreedFull = "BREED_ANDALUSIAN_ROSEGRAY",
                Coat = "COAT_ROSEGREY",
            },
            {
                Model = "A_C_HORSE_ANDALUSIAN_PERLINO",
                Catalog = "HORSE_BREED_ANDALUSIAN_PERLINO",
                BreedShort = "BREED_ANDALUSIAN",
                BreedFull = "BREED_ANDALUSIAN_PERLINO",
                Coat = "COAT_PERLINO",
            },
            {
                Model = "A_C_HORSE_ARDENNES_BAYROAN",
                Catalog = "HORSE_BREED_ARDENNES_BAYROAN",
                BreedShort = "BREED_ARDENNES",
                BreedFull = "BREED_ARDENNES_BAYROAN",
                Coat = "COAT_BAYR",
            },
            {
                Model = "A_C_HORSE_ARDENNES_STRAWBERRYROAN",
                Catalog = "HORSE_BREED_ARDENNES_STRAWBERRYROAN",
                BreedShort = "BREED_ARDENNES",
                BreedFull = "BREED_ARDENNES_STRAWBERRYROAN",
                Coat = "COAT_STRAWR",
            },
            {
                Model = "A_C_HORSE_HUNGARIANHALFBRED_FLAXENCHESTNUT",
                Catalog = "HORSE_BREED_HUNGARIANHALFBRED_FLAXENCHESTNUT",
                BreedShort = "BREED_HUNGARIANHALFBRED",
                BreedFull = "BREED_HUNGARIANHALFBRED_FLAXENCHESTNUT",
                Coat = "COAT_FLAXCH",
            },
            {
                Model = "A_C_HORSE_HUNGARIANHALFBRED_PIEBALDTOBIANO",
                Catalog = "HORSE_BREED_HUNGARIANHALFBRED_PIEBALDTOBIANO",
                BreedShort = "BREED_HUNGARIANHALFBRED",
                BreedFull = "BREED_HUNGARIANHALFBRED_PIEBALDTOBIANO",
                Coat = "COAT_PIETOB",
            },
            {
                Model = "A_C_HORSE_HUNGARIANHALFBRED_DARKDAPPLEGREY",
                Catalog = "HORSE_BREED_HUNGARIANHALFBRED_DARKDAPPLEGREY",
                BreedShort = "BREED_HUNGARIANHALFBRED",
                BreedFull = "BREED_HUNGARIANHALFBRED_DARKDAPPLEGREY",
                Coat = "COAT_DAPDARKGREY",
            },
            {
                Model = "A_C_HORSE_HUNGARIANHALFBRED_LIVERCHESTNUT",
                Catalog = "HORSE_BREED_HUNGARIANHALFBRED_LIVERCHESTNUT",
                BreedShort = "BREED_HUNGARIANHALFBRED",
                BreedFull = "BREED_HUNGARIANHALFBRED_LIVERCHESTNUT",
                Coat = "COAT_LIVERCH",
            },
            {
                Model = "A_C_HORSE_ARDENNES_IRONGREYROAN",
                Catalog = nil,
                BreedShort = "BREED_ARDENNES",
                BreedFull = "BREED_ARDENNES_IRONGREYROAN",
                Coat = "COAT_IRONGREYR",
            }
        }
    },
    {
        Class = "HORSE_CLASS_WORK",
        Items = {
            {
                Model = "A_C_HORSE_AMERICANPAINT_OVERO",
                Catalog = "HORSE_BREED_AMERICANPAINT_OVERO",
                BreedShort = "BREED_AMERICANPAINT",
                BreedFull = "BREED_AMERICANPAINT_OVERO",
                Coat = "COAT_OVERO",
            },
            {
                Model = "A_C_HORSE_AMERICANPAINT_TOBIANO",
                Catalog = "HORSE_BREED_AMERICANPAINT_TOBIANO",
                BreedShort = "BREED_AMERICANPAINT",
                BreedFull = "BREED_AMERICANPAINT_TOBIANO",
                Coat = "COAT_TOB",
            },
            {
                Model = "A_C_HORSE_AMERICANPAINT_SPLASHEDWHITE",
                Catalog = "HORSE_BREED_AMERICANPAINT_SPLASHEDWHITE",
                BreedShort = "BREED_AMERICANPAINT",
                BreedFull = "BREED_AMERICANPAINT_SPLASHEDWHITE",
                Coat = "COAT_SPLASHWHITE",
            },
            {
                Model = "A_C_HORSE_AMERICANPAINT_GREYOVERO",
                Catalog = "HORSE_BREED_AMERICANPAINT_GREYOVERO",
                BreedShort = "BREED_AMERICANPAINT",
                BreedFull = "BREED_AMERICANPAINT_GREYOVERO",
                Coat = "COAT_GREYOVERO",
            },
            {
                Model = "A_C_HORSE_APPALOOSA_BLANKET",
                Catalog = "HORSE_BREED_APPALOOSA_BLANKET",
                BreedShort = "BREED_APPALOOSA",
                BreedFull = "BREED_APPALOOSA_BLANKET",
                Coat = "COAT_BLANKET",
            },
            {
                Model = "A_C_HORSE_APPALOOSA_LEOPARDBLANKET",
                Catalog = "HORSE_BREED_APPALOOSA_LEOPARDBLANKET",
                BreedShort = "BREED_APPALOOSA",
                BreedFull = "BREED_APPALOOSA_LEOPARDBLANKET",
                Coat = "COAT_LEOPBLANKET",
            },
            {
                Model = "A_C_HORSE_APPALOOSA_BROWNLEOPARD",
                Catalog = "HORSE_BREED_APPALOOSA_BROWNLEOPARD",
                BreedShort = "BREED_APPALOOSA",
                BreedFull = "BREED_APPALOOSA_BROWNLEOPARD",
                Coat = "COAT_BRLEOP",
            },
            {
                Model = "A_C_HORSE_APPALOOSA_LEOPARD",
                Catalog = "HORSE_BREED_APPALOOSA_LEOPARD",
                BreedShort = "BREED_APPALOOSA",
                BreedFull = "BREED_APPALOOSA_LEOPARD",
                Coat = "COAT_LEOP",
            },
            {
                Model = "A_C_HORSE_DUTCHWARMBLOOD_SOOTYBUCKSKIN",
                Catalog = "HORSE_BREED_DUTCHWARMBLOOD_SOOTYBUCKSKIN",
                BreedShort = "BREED_DUTCHWARMBLOOD",
                BreedFull = "BREED_DUTCHWARMBLOOD_SOOTYBUCKSKIN",
                Coat = "COAT_SOOTYBUCKSKIN",
            },
            {
                Model = "A_C_HORSE_DUTCHWARMBLOOD_SEALBROWN",
                Catalog = "HORSE_BREED_DUTCHWARMBLOOD_SEALBROWN",
                BreedShort = "BREED_DUTCHWARMBLOOD",
                BreedFull = "BREED_DUTCHWARMBLOOD_SEALBROWN",
                Coat = "COAT_SEALBR",
            },
            {
                Model = "A_C_HORSE_DUTCHWARMBLOOD_CHOCOLATEROAN",
                Catalog = "HORSE_BREED_DUTCHWARMBLOOD_CHOCOLATEROAN",
                BreedShort = "BREED_DUTCHWARMBLOOD",
                BreedFull = "BREED_DUTCHWARMBLOOD_CHOCOLATEROAN",
                Coat = "COAT_CHOCR",
            },
            {
                Model = "A_C_HORSE_APPALOOSA_BLACKSNOWFLAKE",
                Catalog = "HORSE_BREED_APPALOOSA_BLACKSNOWFLAKE",
                BreedShort = "BREED_APPALOOSA",
                BreedFull = "BREED_APPALOOSA_BLACKSNOWFLAKE",
                Coat = "COAT_BLACKSNO",
            },
            {
                Model = "A_C_HORSE_MURFREEBROOD_MANGE_03",
                Catalog = "HORSE_BREED_MURFREEBROOD_MANGE_03",
                BreedShort = "BREED_APPALOOSA",
                BreedFull = "BREED_MURFREEBROOD_MANGE_03",
                Coat = "COAT_BLACKRAB",
            }
        }
    },
    {
        Class = "HORSE_CLASS_MULTI",
        Items = {
            {
                Model = "A_C_HORSE_MISSOURIFOXTROTTER_AMBERCHAMPAGNE",
                Catalog = "HORSE_BREED_MISSOURIFOXTROTTER_AMBERCHAMPAGNE",
                BreedShort = "BREED_MISSOURIFOXTROTTER",
                BreedFull = "BREED_MISSOURIFOXTROTTER_AMBERCHAMPAGNE",
                Coat = "COAT_AMBCHA",
            },
            {
                Model = "A_C_HORSE_MISSOURIFOXTROTTER_SILVERDAPPLEPINTO",
                Catalog = "HORSE_BREED_MISSOURIFOXTROTTER_SILVERDAPPLEPINTO",
                BreedShort = "BREED_MISSOURIFOXTROTTER",
                BreedFull = "BREED_MISSOURIFOXTROTTER_SILVERDAPPLEPINTO",
                Coat = "COAT_SILVERDAPPINT",
            },
            {
                Model = "A_C_HORSE_MUSTANG_GRULLODUN",
                Catalog = "HORSE_BREED_MUSTANG_GRULLODUN",
                BreedShort = "BREED_MUSTANG",
                BreedFull = "BREED_MUSTANG_GRULLODUN",
                Coat = "COAT_GRULDUN",
            },
            {
                Model = "A_C_HORSE_MUSTANG_WILDBAY",
                Catalog = "HORSE_BREED_MUSTANG_WILDBAY",
                BreedShort = "BREED_MUSTANG",
                BreedFull = "BREED_MUSTANG_WILDBAY",
                Coat = "COAT_WILDBAY",
            },
            {
                Model = "A_C_HORSE_MUSTANG_TIGERSTRIPEDBAY",
                Catalog = "HORSE_BREED_MUSTANG_TIGERSTRIPEDBAY",
                BreedShort = "BREED_MUSTANG",
                BreedFull = "BREED_MUSTANG_TIGERSTRIPEDBAY",
                Coat = "COAT_TIGSTRBAY",
            },
            {
                Model = "A_C_HORSE_TURKOMAN_DARKBAY",
                Catalog = "HORSE_BREED_TURKOMAN_DARKBAY",
                BreedShort = "BREED_TURKOMAN",
                BreedFull = "BREED_TURKOMAN_DARKBAY",
                Coat = "COAT_DARKBAY",
            },
            {
                Model = "A_C_HORSE_TURKOMAN_GOLD",
                Catalog = "HORSE_BREED_TURKOMAN_GOLD",
                BreedShort = "BREED_TURKOMAN",
                BreedFull = "BREED_TURKOMAN_GOLD",
                Coat = "COAT_GOLD",
            },
            {
                Model = "A_C_HORSE_TURKOMAN_SILVER",
                Catalog = "HORSE_BREED_TURKOMAN_SILVER",
                BreedShort = "BREED_TURKOMAN",
                BreedFull = "BREED_TURKOMAN_SILVER",
                Coat = "COAT_SILVER",
            },
            {
                Model = "A_C_HORSE_BRETON_REDROAN",
                Catalog = "HORSE_BREED_BRETON_REDROAN",
                BreedShort = "BREED_BRETON",
                BreedFull = "BREED_BRETON_REDROAN",
                Coat = "COAT_REDR",
            },
            {
                Model = "A_C_HORSE_BRETON_SORREL",
                Catalog = "HORSE_BREED_BRETON_SORREL",
                BreedShort = "BREED_BRETON",
                BreedFull = "BREED_BRETON_SORREL",
                Coat = "COAT_SORREL",
            },
            {
                Model = "A_C_HORSE_BRETON_GRULLODUN",
                Catalog = "HORSE_BREED_BRETON_GRULLODUN",
                BreedShort = "BREED_BRETON",
                BreedFull = "BREED_BRETON_GRULLODUN",
                Coat = "COAT_GRULDUN",
            },
            {
                Model = "A_C_HORSE_BRETON_SEALBROWN",
                Catalog = "HORSE_BREED_BRETON_SEALBROWN",
                BreedShort = "BREED_BRETON",
                BreedFull = "BREED_BRETON_SEALBROWN",
                Coat = "COAT_SEALBR",
            },
            {
                Model = "A_C_HORSE_BRETON_MEALYDAPPLEBAY",
                Catalog = "HORSE_BREED_BRETON_MEALYDAPPLEBAY",
                BreedShort = "BREED_BRETON",
                BreedFull = "BREED_BRETON_MEALYDAPPLEBAY",
                Coat = "COAT_MEALYDAPBAY",
            },
            {
                Model = "A_C_HORSE_BRETON_STEELGREY",
                Catalog = "HORSE_BREED_BRETON_STEELGREY",
                BreedShort = "BREED_BRETON",
                BreedFull = "BREED_BRETON_STEELGREY",
                Coat = "COAT_STEELGREY",
            },
            {
                Model = "A_C_HORSE_CRIOLLO_BLUEROANOVERO",
                Catalog = "HORSE_BREED_CRIOLLO_BLUEROANOVERO",
                BreedShort = "BREED_CRIOLLO",
                BreedFull = "BREED_CRIOLLO_BLUEROANOVERO",
                Coat = "COAT_BLUEROANOVERO",
            },
            {
                Model = "A_C_HORSE_CRIOLLO_DUN",
                Catalog = "HORSE_BREED_CRIOLLO_DUN",
                BreedShort = "BREED_CRIOLLO",
                BreedFull = "BREED_CRIOLLO_DUN",
                Coat = "COAT_DUN",
            },
            {
                Model = "A_C_HORSE_CRIOLLO_BAYBRINDLE",
                Catalog = "HORSE_BREED_CRIOLLO_BAYBRINDLE",
                BreedShort = "BREED_CRIOLLO",
                BreedFull = "BREED_CRIOLLO_BAYBRINDLE",
                Coat = "COAT_BAYBRINDLE",
            },
            {
                Model = "A_C_HORSE_CRIOLLO_SORRELOVERO",
                Catalog = "HORSE_BREED_CRIOLLO_SORRELOVERO",
                BreedShort = "BREED_CRIOLLO",
                BreedFull = "BREED_CRIOLLO_SORRELOVERO",
                Coat = "COAT_SORRELOVERO",
            },
            {
                Model = "A_C_HORSE_CRIOLLO_BAYFRAMEOVERO",
                Catalog = "HORSE_BREED_CRIOLLO_BAYFRAMEOVERO",
                BreedShort = "BREED_CRIOLLO",
                BreedFull = "BREED_CRIOLLO_BAYFRAMEOVERO",
                Coat = "COAT_BAYFRAMEOVERO",
            },
            {
                Model = "A_C_HORSE_CRIOLLO_MARBLESABINO",
                Catalog = "HORSE_BREED_CRIOLLO_MARBLESABINO",
                BreedShort = "BREED_CRIOLLO",
                BreedFull = "BREED_CRIOLLO_MARBLESABINO",
                Coat = "COAT_MARBLESABINO",
            },
            {
                Model = "A_C_HORSE_GYPSYCOB_PIEBALD",
                Catalog = "HORSE_BREED_GYPSYCOB_PIEBALD",
                BreedShort = "BREED_GYPSYCOB",
                BreedFull = "BREED_GYPSYCOB_PIEBALD",
                Coat = "COAT_PIE",
            },
            {
                Model = "A_C_HORSE_GYPSYCOB_WHITEBLAGDON",
                Catalog = "HORSE_BREED_GYPSYCOB_WHITEBLAGDON",
                BreedShort = "BREED_GYPSYCOB",
                BreedFull = "BREED_GYPSYCOB_WHITEBLAGDON",
                Coat = "COAT_WHITEBLAGDON",
            },
            {
                Model = "A_C_HORSE_GYPSYCOB_PALOMINOBLAGDON",
                Catalog = "HORSE_BREED_GYPSYCOB_PALOMINOBLAGDON",
                BreedShort = "BREED_GYPSYCOB",
                BreedFull = "BREED_GYPSYCOB_PALOMINOBLAGDON",
                Coat = "COAT_PALBLAGDON",
            },
            {
                Model = "A_C_HORSE_GYPSYCOB_SKEWBALD",
                Catalog = "HORSE_BREED_GYPSYCOB_SKEWBALD",
                BreedShort = "BREED_GYPSYCOB",
                BreedFull = "BREED_GYPSYCOB_SKEWBALD",
                Coat = "COAT_SKEWBALD",
            },
            {
                Model = "A_C_HORSE_GYPSYCOB_SPLASHEDBAY",
                Catalog = "HORSE_BREED_GYPSYCOB_SPLASHEDBAY",
                BreedShort = "BREED_GYPSYCOB",
                BreedFull = "BREED_GYPSYCOB_SPLASHEDBAY",
                Coat = "COAT_SPLASHBAY",
            },
            {
                Model = "A_C_HORSE_GYPSYCOB_SPLASHEDPIEBALD",
                Catalog = "HORSE_BREED_GYPSYCOB_SPLASHEDPIEBALD",
                BreedShort = "BREED_GYPSYCOB",
                BreedFull = "BREED_GYPSYCOB_SPLASHEDPIEBALD",
                Coat = "COAT_SPLASHPIE",
            },
            {
                Model = "A_C_HORSE_KLADRUBER_BLACK",
                Catalog = "HORSE_BREED_KLADRUBER_BLACK",
                BreedShort = "BREED_KLADRUBER",
                BreedFull = "BREED_KLADRUBER_BLACK",
                Coat = "COAT_BLACK",
            },
            {
                Model = "A_C_HORSE_KLADRUBER_WHITE",
                Catalog = "HORSE_BREED_KLADRUBER_WHITE",
                BreedShort = "BREED_KLADRUBER",
                BreedFull = "BREED_KLADRUBER_WHITE",
                Coat = "COAT_WHITE",
            },
            {
                Model = "A_C_HORSE_KLADRUBER_CREMELLO",
                Catalog = "HORSE_BREED_KLADRUBER_CREMELLO",
                BreedShort = "BREED_KLADRUBER",
                BreedFull = "BREED_KLADRUBER_CREMELLO",
                Coat = "COAT_CREM",
            },
            {
                Model = "A_C_HORSE_KLADRUBER_GREY",
                Catalog = "HORSE_BREED_KLADRUBER_GREY",
                BreedShort = "BREED_KLADRUBER",
                BreedFull = "BREED_KLADRUBER_GREY",
                Coat = "COAT_GREY",
            },
            {
                Model = "A_C_HORSE_KLADRUBER_DAPPLEROSEGREY",
                Catalog = "HORSE_BREED_KLADRUBER_DAPPLEROSEGREY",
                BreedShort = "BREED_KLADRUBER",
                BreedFull = "BREED_KLADRUBER_DAPPLEROSEGREY",
                Coat = "COAT_DAPROSEGREY",
            },
            {
                Model = "A_C_HORSE_KLADRUBER_SILVER",
                Catalog = "HORSE_BREED_KLADRUBER_SILVER",
                BreedShort = "BREED_KLADRUBER",
                BreedFull = "BREED_KLADRUBER_SILVER",
                Coat = "COAT_SILVER",
            },
            {
                Model = "A_C_HORSE_NORFOLKROADSTER_BLACK",
                Catalog = "HORSE_BREED_NORFOLKROADSTER_BLACK",
                BreedShort = "BREED_NORFOLKROADSTER",
                BreedFull = "BREED_NORFOLKROADSTER_BLACK",
                Coat = "COAT_BLACK",
            },
            {
                Model = "A_C_HORSE_NORFOLKROADSTER_SPECKLEDGREY",
                Catalog = "HORSE_BREED_NORFOLKROADSTER_SPECKLEDGREY",
                BreedShort = "BREED_NORFOLKROADSTER",
                BreedFull = "BREED_NORFOLKROADSTER_SPECKLEDGREY",
                Coat = "COAT_SPECKLEDGREY",
            },
            {
                Model = "A_C_HORSE_NORFOLKROADSTER_PIEBALDROAN",
                Catalog = "HORSE_BREED_NORFOLKROADSTER_PIEBALDROAN",
                BreedShort = "BREED_NORFOLKROADSTER",
                BreedFull = "BREED_NORFOLKROADSTER_PIEBALDROAN",
                Coat = "COAT_PIEROAN",
            },
            {
                Model = "A_C_HORSE_NORFOLKROADSTER_ROSEGREY",
                Catalog = "HORSE_BREED_NORFOLKROADSTER_ROSEGREY",
                BreedShort = "BREED_NORFOLKROADSTER",
                BreedFull = "BREED_NORFOLKROADSTER_ROSEGREY",
                Coat = "COAT_ROSEGREY",
            },
            {
                Model = "A_C_HORSE_NORFOLKROADSTER_DAPPLEDBUCKSKIN",
                Catalog = "HORSE_BREED_NORFOLKROADSTER_DAPPLEDBUCKSKIN",
                BreedShort = "BREED_NORFOLKROADSTER",
                BreedFull = "BREED_NORFOLKROADSTER_DAPPLEDBUCKSKIN",
                Coat = "COAT_DAPBUCKSKIN",
            },
            {
                Model = "A_C_HORSE_NORFOLKROADSTER_SPOTTEDTRICOLOR",
                Catalog = "HORSE_BREED_NORFOLKROADSTER_SPOTTEDTRICOLOR",
                BreedShort = "BREED_NORFOLKROADSTER",
                BreedFull = "BREED_NORFOLKROADSTER_SPOTTEDTRICOLOR",
                Coat = "COAT_SPOTTEDTRICOLOR",
            },
            {
                Model = "A_C_HORSE_MISSOURIFOXTROTTER_BLACKTOVERO",
                Catalog = "HORSE_BREED_MISSOURIFOXTROTTER_BLACKTOVERO",
                BreedShort = "BREED_MISSOURIFOXTROTTER",
                BreedFull = "BREED_MISSOURIFOXTROTTER_BLACKTOVERO",
                Coat = "COAT_BLACKTOVERO",
            },
            {
                Model = "A_C_HORSE_MISSOURIFOXTROTTER_BLUEROAN",
                Catalog = "HORSE_BREED_MISSOURIFOXTROTTER_BLUEROAN",
                BreedShort = "BREED_MISSOURIFOXTROTTER",
                BreedFull = "BREED_MISSOURIFOXTROTTER_BLUEROAN",
                Coat = "COAT_BLUER",
            },
            {
                Model = "A_C_HORSE_MISSOURIFOXTROTTER_BUCKSKINBRINDLE",
                Catalog = "HORSE_BREED_MISSOURIFOXTROTTER_BUCKSKINBRINDLE",
                BreedShort = "BREED_MISSOURIFOXTROTTER",
                BreedFull = "BREED_MISSOURIFOXTROTTER_BUCKSKINBRINDLE",
                Coat = "COAT_BUCKSKINBRINDLE",
            },
            {
                Model = "A_C_HORSE_MISSOURIFOXTROTTER_DAPPLEGREY",
                Catalog = "HORSE_BREED_MISSOURIFOXTROTTER_DAPPLEGREY",
                BreedShort = "BREED_MISSOURIFOXTROTTER",
                BreedFull = "BREED_MISSOURIFOXTROTTER_DAPPLEGREY",
                Coat = "COAT_DAPGREY",
            },
            {
                Model = "A_C_HORSE_MUSTANG_BLACKOVERO",
                Catalog = "HORSE_BREED_MUSTANG_BLACKOVERO",
                BreedShort = "BREED_MUSTANG",
                BreedFull = "BREED_MUSTANG_BLACKOVERO",
                Coat = "COAT_BLACKOVERO",
            },
            {
                Model = "A_C_HORSE_MUSTANG_BUCKSKIN",
                Catalog = "HORSE_BREED_MUSTANG_BUCKSKIN",
                BreedShort = "BREED_MUSTANG",
                BreedFull = "BREED_MUSTANG_BUCKSKIN",
                Coat = "COAT_BUCKSKIN",
            },
            {
                Model = "A_C_HORSE_MUSTANG_CHESTNUTTOVERO",
                Catalog = "HORSE_BREED_MUSTANG_CHESTNUTTOVERO",
                BreedShort = "BREED_MUSTANG",
                BreedFull = "BREED_MUSTANG_CHESTNUTTOVERO",
                Coat = "COAT_CHTOVERO",
            },
            {
                Model = "A_C_HORSE_MUSTANG_REDDUNOVERO",
                Catalog = "HORSE_BREED_MUSTANG_REDDUNOVERO",
                BreedShort = "BREED_MUSTANG",
                BreedFull = "BREED_MUSTANG_REDDUNOVERO",
                Coat = "COAT_REDDUNOVERO",
            },
            {
                Model = "A_C_HORSE_TURKOMAN_BLACK",
                Catalog = "HORSE_BREED_TURKOMAN_BLACK",
                BreedShort = "BREED_TURKOMAN",
                BreedFull = "BREED_TURKOMAN_BLACK",
                Coat = "COAT_BLACK",
            },
            {
                Model = "A_C_HORSE_TURKOMAN_CHESTNUT",
                Catalog = "HORSE_BREED_TURKOMAN_CHESTNUT",
                BreedShort = "BREED_TURKOMAN",
                BreedFull = "BREED_TURKOMAN_CHESTNUT",
                Coat = "COAT_CH",
            },
            {
                Model = "A_C_HORSE_TURKOMAN_GREY",
                Catalog = "HORSE_BREED_TURKOMAN_GREY",
                BreedShort = "BREED_TURKOMAN",
                BreedFull = "BREED_TURKOMAN_GREY",
                Coat = "COAT_GREY",
            },
            {
                Model = "A_C_HORSE_TURKOMAN_PERLINO",
                Catalog = "HORSE_BREED_TURKOMAN_PERLINO",
                BreedShort = "BREED_TURKOMAN",
                BreedFull = "BREED_TURKOMAN_PERLINO",
                Coat = "COAT_PERLINO",
            },
            {
                Model = "A_C_HORSE_MISSOURIFOXTROTTER_SABLECHAMPAGNE",
                Catalog = "HORSE_BREED_MISSOURIFOXTROTTER_SABLECHAMPAGNE",
                BreedShort = "BREED_MISSOURIFOXTROTTER",
                BreedFull = "BREED_MISSOURIFOXTROTTER_SABLECHAMPAGNE",
                Coat = "COAT_SABLECHAMP",
            },
            {
                Model = "A_C_HORSE_MUSTANG_GOLDENDUN",
                Catalog = "HORSE_BREED_MUSTANG_GOLDENDUN",
                BreedShort = "BREED_MUSTANG",
                BreedFull = "BREED_MUSTANG_GOLDENDUN",
                Coat = "COAT_GOLDENDUN",
            }
        }
    },
    {
        Class = "HORSE_CLASS_SUPERIOR",
        Items = {
            {
                Model = "A_C_HORSE_ARABIAN_BLACK",
                Catalog = "HORSE_BREED_ARABIAN_BLACK",
                BreedShort = "BREED_ARABIAN",
                BreedFull = "BREED_ARABIAN_BLACK",
                Coat = "COAT_BLACK",
            },
            {
                Model = "A_C_HORSE_ARABIAN_ROSEGREYBAY",
                Catalog = "HORSE_BREED_ARABIAN_ROSEGREYBAY",
                BreedShort = "BREED_ARABIAN",
                BreedFull = "BREED_ARABIAN_ROSEGREYBAY",
                Coat = "COAT_ROSEGREYBAY",
            },
            {
                Model = "A_C_HORSE_ARABIAN_WHITE",
                Catalog = "HORSE_BREED_ARABIAN_WHITE",
                BreedShort = "BREED_ARABIAN",
                BreedFull = "BREED_ARABIAN_WHITE",
                Coat = "COAT_WHITE",
            },
            {
                Model = "A_C_HORSE_ARABIAN_GREY",
                Catalog = "HORSE_BREED_ARABIAN_GREY",
                BreedShort = "BREED_ARABIAN",
                BreedFull = "BREED_ARABIAN_GREY",
                Coat = "COAT_GREY",
            },
            {
                Model = "A_C_HORSE_ARABIAN_REDCHESTNUT",
                Catalog = "HORSE_BREED_ARABIAN_REDCHESTNUT",
                BreedShort = "BREED_ARABIAN",
                BreedFull = "BREED_ARABIAN_REDCHESTNUT",
                Coat = "COAT_REDCH",
            }
        }
    },
    {
        Class = "HORSE_CLASS_OTHER",
        Items = {
            {
                Model = "A_C_DONKEY_01",
                Catalog = "HORSE_DONKEY",
                BreedShort = "BREED_DONKEY",
                BreedFull = "BREED_DONKEY",
                Coat = "BREED_DONKEY",
            },
            {
                Model = "A_C_HORSEMULE_01",
                Catalog = nil,
                BreedShort = "BREED_MULE",
                BreedFull = "BREED_MULE",
                Coat = "BREED_MULE",
            },
            {
                Model = "A_C_HORSEMULEPAINTED_01",
                Catalog = nil,
                BreedShort = "BREED_MULE",
                BreedFull = "BREED_MULE_PAINTED",
                Coat = "BREED_MULE_PAINTED",
            }
        }
    },
}

local HORSE_EQUIPMENT <const> = {
    -- Tack
    SADDLES = {
        "HORSE_EQUIPMENT_NATURALISTSADDLE_001_IMPROVED_NEW_SADDLE_000",
        "HORSE_EQUIPMENT_MOONSHINERSADDLE_001_IMPROVED_NEW_SADDLE_000",
        0x51314715,
        0x98C71B0F,
        0x791482E6,
        0x219DE87C,
        0xD913227B,
        0xEF544EFD,
        0xB43058B6,
        { Id = 0x9FB5F98C, Items = { 0xFC6B6539, 0x6658B9D0 } },
        { Id = 0x8ADD75A2, Items = { 0x5E06EF82, 0x39B8D849 } },
        { Id = 0xB5047A43, Items = { 0xF5E33D0B, 0xA07B262E } },
        { Id = 0x3D7E2871, Items = { 0xDAA18259, 0xC12840B6 } },
        { Id = 0xE04D2FE5, Items = { 0x3BB5F150, 0xFF9C1D78 } },
        { Id = 0x2A094F30, Items = { 0xC028C5F0, 0x6749BD20 } },
        { Id = 0x462E31C5, Items = { 0x31A7C792, 0x734E76D4 } },
        0x6F757ECB
    },
    SADDLEBAGS = {
        { Id = 0x5BB6798C, Items = { 0xD8D67396, 0xEB1B7196 } },
        { Id = 0xB28BAE3D, Items = { 0x172D717E, 0x5587C4A2 } },
        { Id = 0x2C0848DC, Items = { 0xBB3BFB09, "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_005_NEW_000", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_006_NEW_000" } },
    },
    STIRRUPS = { "HORSE_EQUIPMENT_STIRRUP_NEW_003", "HORSE_EQUIPMENT_STIRRUP_NEW_004", "HORSE_EQUIPMENT_STIRRUP_NEW_006", "HORSE_EQUIPMENT_STIRRUP_NEW_002", "HORSE_EQUIPMENT_STIRRUP_NEW_001", "HORSE_EQUIPMENT_STIRRUP_NEW_000", "HORSE_EQUIPMENT_STIRRUP_NEW_005", "HORSE_EQUIPMENT_STIRRUP_NEW_010", "HORSE_EQUIPMENT_STIRRUP_NEW_008", "HORSE_EQUIPMENT_STIRRUP_NEW_007", "HORSE_EQUIPMENT_STIRRUP_NEW_009" },
    HORNS = { "HORSE_EQUIPMENT_HORN_NEW_014", "HORSE_EQUIPMENT_HORN_NEW_015", "HORSE_EQUIPMENT_HORN_NEW_016", "HORSE_EQUIPMENT_HORN_NEW_017", "HORSE_EQUIPMENT_HORN_NEW_018", "HORSE_EQUIPMENT_HORN_NEW_019", "HORSE_EQUIPMENT_HORN_NEW_020", "HORSE_EQUIPMENT_HORN_NEW_021", "HORSE_EQUIPMENT_HORN_NEW_022", "HORSE_EQUIPMENT_HORN_NEW_023", "HORSE_EQUIPMENT_HORN_NEW_000", "HORSE_EQUIPMENT_HORN_NEW_001", "HORSE_EQUIPMENT_HORN_NEW_002", "HORSE_EQUIPMENT_HORN_NEW_003", "HORSE_EQUIPMENT_HORN_NEW_004", "HORSE_EQUIPMENT_HORN_NEW_005", "HORSE_EQUIPMENT_HORN_NEW_006", "HORSE_EQUIPMENT_HORN_NEW_007", "HORSE_EQUIPMENT_HORN_NEW_008", "HORSE_EQUIPMENT_HORN_NEW_009", "HORSE_EQUIPMENT_HORN_NEW_010", "HORSE_EQUIPMENT_HORN_NEW_011", "HORSE_EQUIPMENT_HORN_NEW_012", "HORSE_EQUIPMENT_HORN_NEW_013" },
    BLANKETS = { 0x8CBFC7DC, 0x85623E10, 0x5977FF7E, 0x44FF2E58, 0x97A2A7DF, 0x9B72D2BA, 0x17A1727D, 0x084930CF, 0x2BAFF39F, 0xAEF082AB, 0x3157087C, 0xA8BB0475 },
    BEDROLLS = { 0x6427193F, 0x277A8099, 0xE7680F42 },
    LANTERNS = { "HORSE_EQUIPMENT_SADDLE_LANTERN_BASIC" },
    MASKS = { 0x53EEEBD4, 0xC4886BDC, 0xD6E279B1, 0x1C04B009, 0x06BC20E6, 0x8AD94050, 0x877FACCF, 0xD99D05B9, 0x7F5365A0 },

    -- Appearance
    MANES = { "HORSE_EQUIPMENT_MANE_DEFAULT", 0x2A966374, 0xC6E3EF88, 0xD709BC9E, 0xB12459A2, 0x3312DE4D, 0xC2CF0F44, 0x33B813E7, 0x184517B4, 0xEFF174DF, 0x0A6AB6C2, 0x61A33959 },
    TAILS = { "HORSE_EQUIPMENT_TAIL_DEFAULT", 0xCD2B5C80, 0xE2112434, 0x4CBCEF25, 0xC7E27022, 0xAB28350C, 0x352A3F7E },
    MUSTACHES = { 0xE49E6ACE, 0x177FDCC9, 0x025FFEF2, 0x6744EE46 },
}

local HORSE_EQUIPMENT_STYLES <const> = {
    -- Saddles
    [0xD913227B] = { 0xC4E32120, 0x6E3AF3D1, 0x6380DE5D, 0x19FFCB58, 0x003897CA, 0x454BA1F7, 0x3A758C4B, 0x73957E8A, 0x56DA4514, 0x7FF31745 },
    [0xEF544EFD] = { 0xB03CD750, 0x9E163303, 0x53739DBF, 0xC1A0FA18, 0x9054977C, 0xFDB0F237 },
    [0xB43058B6] = { 0xE1430217, 0x622583DE, 0x77A4AEDC, 0x846B4869, 0x9C2977E5, 0x5EC8FD2D },
    [0xFC6B6539] = { "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_NEW_SADDLE_000", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_NEW_SADDLE_001", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_NEW_SADDLE_002", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_NEW_SADDLE_003", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_NEW_SADDLE_004", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_NEW_SADDLE_005", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_USED_SADDLE_000", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_USED_SADDLE_001", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_USED_SADDLE_002", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_USED_SADDLE_003", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_USED_SADDLE_004", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_STOCK_USED_SADDLE_005" },
    [0x6658B9D0] = { "HORSE_EQUIPMENT_MOTHERHUBBARD_01_IMPROVED_NEW_SADDLE_000", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_IMPROVED_NEW_SADDLE_001", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_IMPROVED_NEW_SADDLE_002", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_IMPROVED_NEW_SADDLE_003", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_IMPROVED_NEW_SADDLE_004", "HORSE_EQUIPMENT_MOTHERHUBBARD_01_IMPROVED_NEW_SADDLE_005" },
    [0x5E06EF82] = { "HORSE_EQUIPMENT_WESTERN_01_STOCK_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_01_STOCK_NEW_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_01_STOCK_NEW_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_01_STOCK_NEW_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_01_STOCK_NEW_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_01_STOCK_NEW_SADDLE_005", "HORSE_EQUIPMENT_WESTERN_01_STOCK_USED_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_01_STOCK_USED_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_01_STOCK_USED_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_01_STOCK_USED_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_01_STOCK_USED_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_01_STOCK_USED_SADDLE_005" },
    [0x39B8D849] = { "HORSE_EQUIPMENT_WESTERN_01_IMPROVED_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_01_IMPROVED_NEW_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_01_IMPROVED_NEW_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_01_IMPROVED_NEW_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_01_IMPROVED_NEW_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_01_IMPROVED_NEW_SADDLE_005" },
    [0xF5E33D0B] = { "HORSE_EQUIPMENT_WESTERN_02_STOCK_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_02_STOCK_NEW_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_02_STOCK_NEW_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_02_STOCK_NEW_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_02_STOCK_NEW_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_02_STOCK_NEW_SADDLE_005", "HORSE_EQUIPMENT_WESTERN_02_STOCK_USED_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_02_STOCK_USED_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_02_STOCK_USED_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_02_STOCK_USED_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_02_STOCK_USED_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_02_STOCK_USED_SADDLE_005" },
    [0xA07B262E] = { "HORSE_EQUIPMENT_WESTERN_02_IMPROVED_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_02_IMPROVED_NEW_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_02_IMPROVED_NEW_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_02_IMPROVED_NEW_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_02_IMPROVED_NEW_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_02_IMPROVED_NEW_SADDLE_005" },
    [0xDAA18259] = { "HORSE_EQUIPMENT_WESTERN_03_STOCK_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_03_STOCK_NEW_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_03_STOCK_NEW_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_03_STOCK_NEW_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_03_STOCK_NEW_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_03_STOCK_NEW_SADDLE_005", "HORSE_EQUIPMENT_WESTERN_03_STOCK_USED_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_03_STOCK_USED_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_03_STOCK_USED_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_03_STOCK_USED_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_03_STOCK_USED_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_03_STOCK_USED_SADDLE_005" },
    [0xC12840B6] = { "HORSE_EQUIPMENT_WESTERN_03_IMPROVED_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_03_IMPROVED_NEW_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_03_IMPROVED_NEW_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_03_IMPROVED_NEW_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_03_IMPROVED_NEW_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_03_IMPROVED_NEW_SADDLE_005" },
    [0x3BB5F150] = { "HORSE_EQUIPMENT_WESTERN_04_STOCK_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_04_STOCK_NEW_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_04_STOCK_NEW_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_04_STOCK_NEW_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_04_STOCK_NEW_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_04_STOCK_NEW_SADDLE_005", "HORSE_EQUIPMENT_WESTERN_04_STOCK_USED_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_04_STOCK_USED_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_04_STOCK_USED_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_04_STOCK_USED_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_04_STOCK_USED_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_04_STOCK_USED_SADDLE_005" },
    [0xFF9C1D78] = { "HORSE_EQUIPMENT_WESTERN_04_IMPROVED_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_04_IMPROVED_NEW_SADDLE_001", "HORSE_EQUIPMENT_WESTERN_04_IMPROVED_NEW_SADDLE_002", "HORSE_EQUIPMENT_WESTERN_04_IMPROVED_NEW_SADDLE_003", "HORSE_EQUIPMENT_WESTERN_04_IMPROVED_NEW_SADDLE_004", "HORSE_EQUIPMENT_WESTERN_04_IMPROVED_NEW_SADDLE_005" },
    [0xC028C5F0] = { "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_NEW_SADDLE_000", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_NEW_SADDLE_001", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_NEW_SADDLE_002", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_NEW_SADDLE_003", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_NEW_SADDLE_004", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_NEW_SADDLE_005", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_USED_SADDLE_000", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_USED_SADDLE_001", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_USED_SADDLE_002", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_USED_SADDLE_003", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_USED_SADDLE_004", "HORSE_EQUIPMENT_MCCLELLAN_01_STOCK_USED_SADDLE_005" },
    [0x6749BD20] = { "HORSE_EQUIPMENT_MCCLELLAN_01_IMPROVED_NEW_SADDLE_000", "HORSE_EQUIPMENT_MCCLELLAN_01_IMPROVED_NEW_SADDLE_001", "HORSE_EQUIPMENT_MCCLELLAN_01_IMPROVED_NEW_SADDLE_002", "HORSE_EQUIPMENT_MCCLELLAN_01_IMPROVED_NEW_SADDLE_003", "HORSE_EQUIPMENT_MCCLELLAN_01_IMPROVED_NEW_SADDLE_004", "HORSE_EQUIPMENT_MCCLELLAN_01_IMPROVED_NEW_SADDLE_005" },
    [0x31A7C792] = { "HORSE_EQUIPMENT_CHARRO_01_STOCK_NEW_SADDLE_000", "HORSE_EQUIPMENT_CHARRO_01_STOCK_NEW_SADDLE_001", "HORSE_EQUIPMENT_CHARRO_01_STOCK_NEW_SADDLE_002", "HORSE_EQUIPMENT_CHARRO_01_STOCK_NEW_SADDLE_003", "HORSE_EQUIPMENT_CHARRO_01_STOCK_NEW_SADDLE_004", "HORSE_EQUIPMENT_CHARRO_01_STOCK_NEW_SADDLE_005", "HORSE_EQUIPMENT_CHARRO_01_STOCK_USED_SADDLE_000", "HORSE_EQUIPMENT_CHARRO_01_STOCK_USED_SADDLE_001", "HORSE_EQUIPMENT_CHARRO_01_STOCK_USED_SADDLE_002", "HORSE_EQUIPMENT_CHARRO_01_STOCK_USED_SADDLE_003", "HORSE_EQUIPMENT_CHARRO_01_STOCK_USED_SADDLE_004", "HORSE_EQUIPMENT_CHARRO_01_STOCK_USED_SADDLE_005" },
    [0x734E76D4] = { "HORSE_EQUIPMENT_CHARRO_01_IMPROVED_NEW_SADDLE_000", "HORSE_EQUIPMENT_CHARRO_01_IMPROVED_NEW_SADDLE_001", "HORSE_EQUIPMENT_CHARRO_01_IMPROVED_NEW_SADDLE_002", "HORSE_EQUIPMENT_CHARRO_01_IMPROVED_NEW_SADDLE_003", "HORSE_EQUIPMENT_CHARRO_01_IMPROVED_NEW_SADDLE_004", "HORSE_EQUIPMENT_CHARRO_01_IMPROVED_NEW_SADDLE_005" },
    [0x6F757ECB] = { "HORSE_EQUIPMENT_MOTHERHUBBARD_01_SPECIAL_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_01_SPECIAL_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_02_SPECIAL_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_03_SPECIAL_NEW_SADDLE_000", "HORSE_EQUIPMENT_WESTERN_04_SPECIAL_NEW_SADDLE_000", "HORSE_EQUIPMENT_MCCLELLAN_01_SPECIAL_NEW_SADDLE_000", "HORSE_EQUIPMENT_CHARRO_01_SPECIAL_NEW_SADDLE_000", "HORSE_EQUIPMENT_HIGHPLAINS_CUTTING_SADDLE_000" },

    -- Saddlebags
    [0xD8D67396] = { 0x18A6655C, 0xEB4D0AAA, 0x5EB0F1DC, 0x34859D86, 0xFB66AB49, 0x513156DD, 0x15DB6032, 0xE77A8371, 0xB251191B, 0x0817C4AB, 0x0C283176, 0x69D2ECCA, 0xFDC114DC, 0x5811C97C, 0x1CE65326, 0x0F2DB7B5, 0xB05AFA15, 0xA2C55EEA, 0x4401A15C, 0x36C306DF, "HORSE_EQUIPMENT_HORSE_SADDLEBAG_NEW_000", "HORSE_EQUIPMENT_HORSE_SADDLEBAG_NEW_001", "HORSE_EQUIPMENT_HORSE_SADDLEBAG_NEW_002", "HORSE_EQUIPMENT_HORSE_SADDLEBAG_NEW_003", "HORSE_EQUIPMENT_HORSE_SADDLEBAG_NEW_004" },
    [0xEB1B7196] = { "HORSE_EQUIPMENT_HORSE_SADDLEBAG_USED_000", "HORSE_EQUIPMENT_HORSE_SADDLEBAG_USED_001", "HORSE_EQUIPMENT_HORSE_SADDLEBAG_USED_002", "HORSE_EQUIPMENT_HORSE_SADDLEBAG_USED_003", "HORSE_EQUIPMENT_HORSE_SADDLEBAG_USED_004" },
    [0x172D717E] = { "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_000", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_001", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_002", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_003", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_004", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_005", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_006", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_007", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_008", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_003_NEW_009", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_000", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_001", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_002", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_003", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_004", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_005", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_006", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_007", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_008", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_004_NEW_009", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_NEW_000", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_NEW_001", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_NEW_002", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_NEW_003", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_NEW_004" },
    [0x5587C4A2] = { "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_USED_000", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_USED_001", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_USED_002", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_USED_003", "HORSE_EQUIPMENT_HORSE_SADDLEBAGUPGRADE_USED_004" },

    -- Blankets
    [0x8CBFC7DC] = { "HORSE_EQUIPMENT_HORSE_BLANKET_00_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_00_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_00_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_00_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_00_NEW_004" },
    [0x85623E10] = { "HORSE_EQUIPMENT_HORSE_BLANKET_01_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_01_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_01_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_01_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_01_NEW_004" },
    [0x5977FF7E] = { "HORSE_EQUIPMENT_HORSE_BLANKET_02_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_02_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_02_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_02_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_02_NEW_004" },
    [0x44FF2E58] = { "HORSE_EQUIPMENT_HORSE_BLANKET_03_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_03_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_03_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_03_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_03_NEW_004" },
    [0x97A2A7DF] = { "HORSE_EQUIPMENT_HORSE_BLANKET_04_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_04_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_04_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_04_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_04_NEW_004" },
    [0x9B72D2BA] = { "HORSE_EQUIPMENT_HORSE_BLANKET_05_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_05_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_05_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_05_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_05_NEW_004" },
    [0x17A1727D] = { "HORSE_EQUIPMENT_HORSE_BLANKET_06_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_06_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_06_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_06_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_06_NEW_004" },
    [0x084930CF] = { "HORSE_EQUIPMENT_HORSE_BLANKET_07_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_07_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_07_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_07_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_07_NEW_004" },
    [0x2BAFF39F] = { "HORSE_EQUIPMENT_HORSE_BLANKET_08_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_08_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_08_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_08_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_08_NEW_004" },
    [0xAEF082AB] = { "HORSE_EQUIPMENT_HORSE_BLANKET_09_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_09_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_09_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_09_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_09_NEW_004" },
    [0x3157087C] = { "HORSE_EQUIPMENT_HORSE_BLANKET_10_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_10_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_10_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_10_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_10_NEW_004" },
    [0xA8BB0475] = { "HORSE_EQUIPMENT_HORSE_BLANKET_11_NEW_000", "HORSE_EQUIPMENT_HORSE_BLANKET_11_NEW_001", "HORSE_EQUIPMENT_HORSE_BLANKET_11_NEW_002", "HORSE_EQUIPMENT_HORSE_BLANKET_11_NEW_003", "HORSE_EQUIPMENT_HORSE_BLANKET_11_NEW_004" },

    -- Bedrolls
    [0x6427193F] = { "HORSE_EQUIPMENT_HORSE_BEDROLL_00_NEW_000", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_NEW_001", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_NEW_002", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_NEW_003", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_NEW_004", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_USED_000", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_USED_001", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_USED_002", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_USED_003", "HORSE_EQUIPMENT_HORSE_BEDROLL_00_USED_004" },
    [0x277A8099] = { "HORSE_EQUIPMENT_HORSE_BEDROLL_01_NEW_000", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_NEW_001", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_NEW_002", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_NEW_003", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_NEW_004", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_USED_000", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_USED_001", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_USED_002", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_USED_003", "HORSE_EQUIPMENT_HORSE_BEDROLL_01_USED_004" },
    [0xE7680F42] = { "HORSE_EQUIPMENT_HORSE_BEDROLL_02_NEW_000", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_NEW_001", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_NEW_002", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_NEW_003", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_NEW_004", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_USED_000", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_USED_001", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_USED_002", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_USED_003", "HORSE_EQUIPMENT_HORSE_BEDROLL_02_USED_004" },

    -- Masks
    [0x1C04B009] = { "HORSE_EQUIPMENT_MASK_NEW_000_TINT_001", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_002", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_003", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_004", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_005", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_006", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_007", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_008", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_009", "HORSE_EQUIPMENT_MASK_NEW_000_TINT_010" },
    [0x06BC20E6] = { "HORSE_EQUIPMENT_MASK_NEW_001_TINT_001", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_002", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_003", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_004", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_005", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_006", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_007", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_008", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_009", "HORSE_EQUIPMENT_MASK_NEW_001_TINT_010" },
    [0x8AD94050] = { "HORSE_EQUIPMENT_MASK_NEW_002_TINT_001", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_002", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_003", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_004", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_005", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_006", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_007", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_008", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_009", "HORSE_EQUIPMENT_MASK_NEW_002_TINT_010" },
    [0x877FACCF] = { "HORSE_EQUIPMENT_MASK_NEW_003_TINT_001", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_002", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_003", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_004", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_005", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_006", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_007", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_008", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_009", "HORSE_EQUIPMENT_MASK_NEW_003_TINT_010" },
    [0xD99D05B9] = { "HORSE_EQUIPMENT_MASK_NEW_004_TINT_001", "HORSE_EQUIPMENT_MASK_NEW_004_TINT_002", "HORSE_EQUIPMENT_MASK_NEW_004_TINT_003", "HORSE_EQUIPMENT_MASK_NEW_004_TINT_004" },
    [0x7F5365A0] = { "HORSE_EQUIPMENT_MASK_NEW_005_TINT_001", "HORSE_EQUIPMENT_MASK_NEW_005_TINT_002", "HORSE_EQUIPMENT_MASK_NEW_005_TINT_003", "HORSE_EQUIPMENT_MASK_NEW_005_TINT_004" },

    -- Manes
    [0x2A966374] = { 0x130E341A, 0xE1435081, 0xA7A4DD49, 0xB5F379E6, 0xEA46E28C, 0xD894BF28, 0x5ED14B9F, 0x6B3A6471, 0x817B10F6, 0x41EA9196, 0xFF020F3A, 0x419D9470, 0x2FCAF0CB, 0x66215D77, 0x5445B9C0, 0x1A5A45B6, 0x16923E26 },
    [0xC6E3EF88] = { 0x86457C9A, 0x99F5A3FA, 0xABA8475F, 0xBD7B6B05, 0x3F1FEE4C, 0x52DC15C8, 0x648A3924, 0x7098D141, 0xF2E555D8, 0x0354F6B7, 0x5DE62AE8, 0x4F148D45, 0xC15371C1, 0xB288D42C, 0xA4E1B8DE, 0x960C1B33, 0x18199F48 },
    [0xD709BC9E] = { 0xC9D16B31, 0x5FE29755, 0xC8646863, 0x5F0395A3, 0x6CB9310E, 0x838E5EB8, 0x0235DBF1, 0x94F58186, 0xAA3FAC1A, 0xB881489D, 0x97D095F4, 0xA193A97A, 0xFC74DF3B, 0x0632F2B7, 0xE0BC27A6, 0x0AFB7C24, 0x446A6F01 },
    [0xB12459A2] = { 0x6F4510C4, 0x7D902D5A, 0x92B2579E, 0xA0F4F423, 0x3BFE2A17, 0x2E378E8A, 0x5D596CCD, 0x4FCC51B3, 0xD4E65BE5, 0x054A3CB0, 0x97105EF6, 0xA64BFD6D, 0xDC62E996, 0xE9FE04D0, 0xB13D134B, 0xCF434F57, 0x25627B98 },
    [0x3312DE4D] = { 0xACA2B4B1, 0x9DF8175C, 0xD43503D5, 0x09836E71, 0x2D47B5FD, 0x8679685F, 0x50AC7CC6, 0x1DF21752, 0xC0085B74, 0xD152FE09, 0xE12C9C64, 0xF304C014, 0xD9CE8DB4, 0x0B52F0BC, 0x388E4B32, 0xEAB72F85, 0x14098229 },
    [0xC2CF0F44] = { 0x3A7C2C86, 0x483AC803, 0x6038F7FF, 0xE02377D6, 0x6D9412B5, 0x83563E39, 0x96FE6589, 0xFFF3B76A, 0x0DCF5321, 0x241D7FBD, 0x0512377B, 0x1FDC6D0F, 0x09A640A3, 0xC929BFA7, 0xB2FB934B, 0xCDC9C8E7, 0xFF17AB82 },
    [0x33B813E7] = { 0xD21B0A64, 0x27D5B5D8, 0x3590514D, 0xEF69C645, 0x09B5FADD, 0xF3724E32 },
    [0x184517B4] = { 0x031FED8D, 0x47F57737, 0xE166AA1B, 0x2881B850, 0x3AC55CD7, 0x7CB2E0D9 },
    [0xEFF174DF] = { 0x102E87AA, 0x1C289C3E, 0x74FE4E10, 0x38BC5565, 0x35744ED1, 0x63222A34 },
    [0x0A6AB6C2] = { 0x3DAC0C59, 0x2C1E693E, 0x7161F3C4, 0x92A63558, 0x4BCA27B1, 0x397F831C, 0x6F28EE6E, 0x5CD349C3, 0x92A3B567, 0x8035108A, 0xB6007C20, 0xA44ED8BD, 0x36A5FD2D, 0x0A7115F0, 0x1B9F384C, 0x7838F17E, 0x8A47959B, 0x427C8606, 0x54F6AAFA, 0xD114A330, 0xE2CF46A5, 0xBD16FB35, 0xCF4C9FA0 },
    [0x61A33959] = { 0x793984BF, 0xA6F8603C, 0xC5F59E3A, 0xF4B77BBD, 0x9F60D111, 0xD01DB28A, 0x2B676918, 0x21AD55A4, 0x073CA0C3, 0xFE878F59, 0x83760A4C, 0x95B8AED1, 0x11C0A6DF, 0xEC1D5B99, 0xFA6BF836, 0xCCA21CA3, 0x6CB65CC5, 0x76787049, 0x54402BD9, 0x25F94F4C, 0x3918F467, 0x075510E0, 0xC3C189AA },

    -- Tails
    [0xCD2B5C80] = { 0xCDFF359A, 0x740701A3, 0xEAA5EEE7, 0xB244FE1E, 0xA0775A83, 0x4B51B039, 0x3D1F13D4, 0x69756C80, 0x574BC82D, 0x066C266F, 0x383E86F3, 0xA4F0E056, 0x9CB1CFD8, 0x894C290D, 0x7A248ABE, 0xED787168, 0xE38F5D96 },
    [0xE2112434] = { 0x543203ED, 0x695B2E3F, 0x2E753874, 0x84ADE4E4, 0x1E9A18C2, 0x75C4C716, 0x3B27D1DD, 0x5062FC53, 0xDCE41557, 0xEAEAB164, 0x0AFB492C, 0x1BB5EAA1, 0x5F4871C5, 0x3D212D77, 0x82DB38EE, 0x508AD44A, 0xC0AF3489 },
    [0x4CBCEF25] = { 0xD7D68A7B, 0x0607E6DD, 0xF4294320, 0x3AE050B5, 0xD9288D47, 0x084D6B90, 0xF4A3443C, 0x810A5CE0, 0x30603BB5, 0x1F7A99EA, 0xC304EB4C, 0xB4374DB1, 0x5D7FA043, 0xEABBBAB9, 0xD9EA1916, 0x073073A2, 0xF867D611 },
    [0xC7E27022] = { 0x33E7B1CB, 0x25B51566, 0xEBC7218B, 0xDDB48566, 0x4F5268A4, 0x4124CC49, 0xC2FA4FF2, 0xB4AB3354, 0xA62C9657, 0x17EB79D3, 0xED0397AC, 0x1A3B721B, 0xC74FCC45, 0xF6B0AB06, 0xA3DA055A, 0xD143E02D, 0xA7438C29 },
    [0xAB28350C] = { 0x12DBBBAF, 0x04951F22, 0x6DB6F164, 0x607956E9, 0x49CD2991, 0x3B8A8D0C, 0xA8A4673A, 0x972AC447, 0x84269E43, 0x96EDC3D1, 0xCE62B5CE, 0xBCD412B1, 0xEFA67855, 0xDD9F5447, 0x876B27E0, 0x7522834F, 0x88A2AA53 },
    [0x352A3F7E] = { 0x162191A0, 0x475D7417, 0xE283AA65, 0x1FE89D6A, 0x4F087BA9, 0x6465A66B },

    -- Mustaches
    [0xE49E6ACE] = { 0x67590D8F, 0xAC459767, 0x9ADAF492, 0xCFBA5E50 },
    [0x177FDCC9] = { 0x5497E784, 0xED8D1970, 0x004BBEED, 0x0960D117 },
    [0x025FFEF2] = { 0x281A6D81, 0xEAEEF32B, 0xDC895660, 0x334F83D3 },
    [0x6744EE46] = { 0x91887491, 0xB755402E, 0xAF2A2FD8, 0xF7203FC3 },
}

_G.INVENTORY_DEMO = INVENTORY_DEMO
_G.HORSES = HORSES
_G.HORSE_EQUIPMENT = HORSE_EQUIPMENT
_G.HORSE_EQUIPMENT_STYLES = HORSE_EQUIPMENT_STYLES
